begin;
select plan(15);
select ok(not has_table_privilege('anon','public.businesses','select'),'anon cannot enumerate businesses');
select ok(not has_table_privilege('anon','public.products','select'),'anon cannot enumerate products');
select ok(not has_table_privilege('anon','public.categories','select'),'anon cannot enumerate categories');
select ok(not has_table_privilege('anon','public.business_members','select'),'anon cannot read memberships');
select ok(not has_table_privilege('anon','public.products','insert,update,delete'),'anon cannot write products');
select ok(has_function_privilege('anon','public.get_public_store(text)','execute'),'anon can open a store by slug');
select ok(not has_function_privilege('anon','public.reorder_catalog_items(uuid,text,uuid[])','execute'),'anon cannot reorder a catalog');
select ok(not has_function_privilege('anon','public.rename_category(uuid,text,text,boolean)','execute'),'anon cannot rename categories');
select ok(has_table_privilege('authenticated','public.businesses','select,update'),'authenticated role has required business grants');
select ok(not has_table_privilege('authenticated','public.businesses','insert,delete'),'authenticated role cannot create or delete businesses directly');
select ok(has_table_privilege('authenticated','public.products','select,insert,update,delete'),'authenticated role has product CRUD grants');
select ok(has_table_privilege('authenticated','public.categories','select,insert,update,delete'),'authenticated role has category CRUD grants');
select ok(has_function_privilege('authenticated','public.reorder_catalog_items(uuid,text,uuid[])','execute'),'authenticated role can call atomic reorder');
select ok(has_function_privilege('authenticated','public.rename_category(uuid,text,text,boolean)','execute'),'authenticated role can call atomic category rename');
select is(public.get_public_store('slug inválido'),null::jsonb,'invalid slugs return no data');
select * from finish();
rollback;
