let adminCategories=[];
const originalApplyCatalog=applyBusiness;
applyBusiness=function(b){originalApplyCatalog(b);document.documentElement.dataset.cardSize=b?.customization?.card_size||'normal'};

loadStore=async function(){
 const slug=new URLSearchParams(location.search).get('tienda')||'bellamujer',business=await fetchBusiness(slug);
 if(!business){activeBusiness=null;products.splice(0);cats.splice(0,cats.length,'Todas');renderCats();render();count.textContent='Tienda no disponible';return}
 applyBusiness(business);
 const [productResult,categoryResult]=await Promise.all([
  supabaseClient.from('products').select('id,name,category,description,price,old_price,sizes,colors,image_url,images,stock,active,sort_order,created_at').eq('business_id',business.id).eq('active',true).order('sort_order').order('created_at',{ascending:false}),
  supabaseClient.from('categories').select('id,name,icon,sort_order,active').eq('business_id',business.id).eq('active',true).order('sort_order')
 ]);
 if(productResult.error){console.error(productResult.error);toast('No se pudo cargar el catálogo');return}
 const categoryRows=categoryResult.data||[];
 products.splice(0,products.length,...(productResult.data||[]).map(p=>({id:p.id,dbId:p.id,name:p.name,cat:p.category,price:Number(p.price),old:Number(p.old_price||0),sizes:p.sizes?.length?p.sizes:['Única'],colors:p.colors?.length?p.colors:['Consultar'],img:p.image_url||p.images?.[0]||makeImg(p.name,'#ead2da','#fff7f9'),images:p.images?.length?p.images:[p.image_url].filter(Boolean),desc:p.description||'',stock:Number(p.stock||0)})));
 const names=categoryRows.map(c=>c.name),extras=products.map(p=>p.cat).filter(n=>!names.includes(n));
 cats.splice(0,cats.length,'Todas',...names,...new Set(extras));window.categoryIcons=Object.fromEntries(categoryRows.map(c=>[c.name,c.icon]));
 if(!cats.includes(selectedCat))selectedCat='Todas';cart=cart.filter(x=>products.some(p=>p.id===x.id));favs=favs.filter(id=>products.some(p=>p.id===id));save();renderCats();render();
};
renderCats=function(){categories.innerHTML=cats.map(c=>`<button class="category-card ${selectedCat===c?'active':''}" data-cat="${escapeHtml(c)}" onclick="setCat(this.dataset.cat)"><span class="cat-icon">${c==='Todas'?'✦':escapeHtml(window.categoryIcons?.[c]||'◇')}</span><strong>${escapeHtml(c)}</strong></button>`).join('')};
render=function(){
 const q=search.value.toLowerCase(),s=size.value,p=Number(priceFilter.value||0);let rows=products.filter(x=>(selectedCat==='Todas'||x.cat===selectedCat)&&(!q||(x.name+' '+x.cat).toLowerCase().includes(q))&&(!s||x.sizes.includes(s))&&(!p||x.price<=p));count.textContent=rows.length+' productos';
 grid.innerHTML=rows.map(x=>`<article class="card"><div class="photo" onclick="openProduct('${x.id}')"><img loading="lazy" decoding="async" src="${escapeHtml(x.img)}" alt="${escapeHtml(x.name)}">${x.old?'<span class="sale">OFERTA</span>':''}${x.stock<=0?'<span class="sale sold">AGOTADO</span>':''}<button class="heart" onclick="event.stopPropagation();toggleFav('${x.id}')">${favs.includes(x.id)?'♥':'♡'}</button></div><div class="card-body"><span class="cat">${escapeHtml(x.cat)}</span><h3>${escapeHtml(x.name)}</h3><div class="price-line"><span class="price">${CLP(x.price)}</span>${x.old?`<span class="old">${CLP(x.old)}</span>`:''}</div><button class="quick" onclick="openProduct('${x.id}')">${x.stock<=0?'Ver producto agotado':'Ver producto'}</button></div></article>`).join('')||'<div class="empty" style="grid-column:1/-1">No encontramos productos con esos filtros.</div>';
};
const originalProductFormCatalog=productForm;
productForm=function(p={}){originalProductFormCatalog(p);const form=document.querySelector('#productForm'),photo=form.querySelector('.photo-editor');
 const categoryInput=form.querySelector('#editCategory'),categorySelect=document.createElement('select');categorySelect.id='editCategory';categorySelect.name='category';categorySelect.required=true;const choices=[...new Set([...adminCategories.filter(c=>c.active).map(c=>c.name),p.category||'Productos'])];categorySelect.innerHTML=choices.map(name=>`<option value="${esc(name)}" ${name===(p.category||'Productos')?'selected':''}>${esc(name)}</option>`).join('');categoryInput.replaceWith(categorySelect);
 const stock=document.createElement('div');stock.className='field';stock.innerHTML=`<label for="editStock">Stock disponible</label><input id="editStock" name="stock" type="number" min="0" step="1" value="${Number(p.stock??0)}"><small>Usa 0 para mostrar Agotado.</small>`;form.querySelector('#editOldPrice').closest('.two-col').after(stock);
 const gallery=document.createElement('div');gallery.className='field';gallery.innerHTML='<label for="galleryFiles">Fotos adicionales</label><input id="galleryFiles" type="file" accept="image/jpeg,image/png,image/webp" multiple><small>Puedes elegir varias fotos. La primera será la principal.</small><div class="gallery-preview"></div>';photo.appendChild(gallery);bindMultiPreview(gallery.querySelector('input'),gallery.querySelector('.gallery-preview'));
 const existing=document.createElement('div'),existingImages=p.images?.length?p.images:[p.image_url].filter(Boolean);existing.className='gallery-admin';existing.innerHTML=existingImages.map((url,i)=>`<label class="gallery-thumb"><img src="${esc(url)}"><input type="checkbox" name="keep_image" value="${esc(url)}" checked> Conservar${i===0?' · principal':''}</label>`).join('');photo.prepend(existing);
};
function bindMultiPreview(input,target){input.onchange=()=>{target.replaceChildren();[...input.files].slice(0,8).forEach(file=>{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)return;const img=document.createElement('img');img.className='image-preview';img.src=URL.createObjectURL(file);target.appendChild(img)})}};
saveProduct=async function(e,id){
 e.preventDefault();const form=e.target,f=new FormData(form),message=form.querySelector('#productMessage');message.textContent='Guardando producto…';
 const uploaded=[];for(const file of [...(form.querySelector('#galleryFiles')?.files||[])].slice(0,8)){const url=await uploadImage(file);if(!url){message.textContent='No se pudieron subir todas las fotos.';return}uploaded.push(url)}
 let images=[...f.getAll('keep_image'),...uploaded];if(form.querySelector('#productFile').files[0]){const url=await uploadImage(form.querySelector('#productFile').files[0]);if(!url)return;images=[url,...images.filter(x=>x!==url)]}
 const payload={business_id:managedBusiness.id,name:String(f.get('name')).trim(),category:String(f.get('category')).trim(),price:Number(f.get('price')),old_price:Number(f.get('old_price')||0),stock:Number(f.get('stock')||0),description:String(f.get('description')).trim(),sizes:list(f.get('sizes')),colors:list(f.get('colors')),images,image_url:images[0]||String(f.get('image_url')||''),active:f.get('active')==='on',updated_at:new Date().toISOString()};
 const query=id?supabaseClient.from('products').update(payload).eq('id',id):supabaseClient.from('products').insert(payload);const {error}=await query;if(error){message.textContent=error.message;return}toast('Producto guardado');await renderProductAdmin();await loadStore();
};

const originalOpenCatalog=openAdminDashboard;
openAdminDashboard=async function(tab='settings'){
 if(window.accessExpired&&activeUser?.id!==SUPERADMIN_USER_ID){closeModal('profileModal');adminModal.classList.add('show');document.body.classList.add('admin-mode');adminContent.innerHTML=`<div class="admin-card expired-access"><p class="eyebrow">Acceso de solo lectura</p><h2>Tu período de administración venció</h2><p>Puedes seguir viendo tu tienda pública. Solicita al propietario que reactive tu acceso para editar productos, categorías y ajustes.</p><button class="btn btn-wine" onclick="openPublicStore()">Ver tienda pública</button></div>`;return}
 await originalOpenCatalog(tab);const tabs=adminContent.querySelector('.admin-tabs');if(!tabs)return;if(!tabs.querySelector('[data-tab=categories]')){const button=document.createElement('button');button.className='admin-tab';button.dataset.tab='categories';button.textContent='Categorías';button.onclick=()=>showAdminTab('categories');tabs.querySelector('[data-tab=share]').before(button);const panel=document.createElement('section');panel.className='admin-panel';panel.dataset.panel='categories';adminContent.appendChild(panel)}await renderCategoryAdmin();if(tab==='categories')showAdminTab('categories')};
async function renderCategoryAdmin(){
 const panel=adminContent.querySelector('[data-panel=categories]');if(!panel)return;const {data,error}=await supabaseClient.from('categories').select('*').eq('business_id',managedBusiness.id).order('sort_order');adminCategories=data||[];
 panel.innerHTML=`<div class="admin-card"><h3>Crear categoría</h3><form id="categoryForm" class="category-form"><input name="name" maxlength="60" placeholder="Ej. Chaquetas" required><input name="icon" maxlength="12" value="◇" aria-label="Icono"><button class="btn btn-wine">Agregar</button></form><p class="help-copy">Puedes escribir un emoji como icono. «Todas» se mantiene automáticamente al comienzo.</p></div><div class="admin-list">${adminCategories.map((c,i)=>`<div class="admin-card category-row"><input value="${esc(c.icon)}" maxlength="12" aria-label="Icono"><input value="${esc(c.name)}" maxlength="60" aria-label="Nombre"><label><input type="checkbox" ${c.active?'checked':''}> Visible</label><div class="small-actions"><button ${i===0?'disabled':''} onclick="moveCategory(${i},-1)">↑</button><button ${i===adminCategories.length-1?'disabled':''} onclick="moveCategory(${i},1)">↓</button><button onclick="saveCategory(${i})">Guardar</button><button class="danger" onclick="deleteCategory('${c.id}')">Eliminar</button></div></div>`).join('')||'<div class="empty">Crea tu primera categoría.</div>'}</div>`;
 panel.querySelector('#categoryForm').onsubmit=createCategory;
}
async function createCategory(e){e.preventDefault();const f=new FormData(e.target);const {error}=await supabaseClient.from('categories').insert({business_id:managedBusiness.id,name:String(f.get('name')).trim(),icon:String(f.get('icon')).trim()||'◇',sort_order:adminCategories.length});if(error)return toast(error.code==='23505'?'La categoría ya existe':error.message);toast('Categoría creada');await renderCategoryAdmin();await loadStore()}
async function saveCategory(i){const card=adminContent.querySelectorAll('.category-row')[i],c=adminCategories[i],inputs=card.querySelectorAll('input');const old=c.name,name=inputs[1].value.trim();const {error}=await supabaseClient.from('categories').update({icon:inputs[0].value.trim()||'◇',name,active:inputs[2].checked}).eq('id',c.id);if(error)return toast(error.message);if(old!==name)await supabaseClient.from('products').update({category:name}).eq('business_id',managedBusiness.id).eq('category',old);toast('Categoría guardada');await renderCategoryAdmin();await loadStore()}
async function moveCategory(i,d){const other=i+d;if(other<0||other>=adminCategories.length)return;await Promise.all([supabaseClient.from('categories').update({sort_order:other}).eq('id',adminCategories[i].id),supabaseClient.from('categories').update({sort_order:i}).eq('id',adminCategories[other].id)]);await renderCategoryAdmin();await loadStore()}
async function deleteCategory(id){const name=adminCategories.find(c=>c.id===id)?.name||'';if(!confirm('¿Eliminar la categoría '+name+'? Los productos seguirán existiendo.'))return;const {error}=await supabaseClient.from('categories').delete().eq('id',id);if(error)return toast(error.message);toast('Categoría eliminada');await renderCategoryAdmin();await loadStore()}

const originalRenderProductsCatalog=renderProductAdmin;
renderProductAdmin=async function(){await originalRenderProductsCatalog();const list=document.querySelector('#adminProductList');list?.querySelectorAll('.admin-product').forEach((row,i)=>{const p=adminProductsCache[i];row.querySelector('small').textContent=(p.active?'Visible':'Oculto')+' · '+p.category+' · Stock '+Number(p.stock||0);const actions=row.querySelector('.small-actions');const duplicate=document.createElement('button');duplicate.textContent='Duplicar';duplicate.onclick=()=>duplicateProduct(i);actions.prepend(duplicate)})};
async function duplicateProduct(i){const p={...adminProductsCache[i]};delete p.id;delete p.created_at;p.name+=' (copia)';p.active=false;const {error}=await supabaseClient.from('products').insert(p);if(error)return toast(error.message);toast('Producto duplicado como oculto');await renderProductAdmin()}

openProduct=function(id){
 current=products.find(p=>String(p.id)===String(id));if(!current)return toast('Este producto ya no está disponible');const variants=(values,type)=>`<div class="chips" data-variant="${type}">${values.map((v,i)=>`<button class="chip ${i===0?'selected':''}" type="button" onclick="pick(this)" aria-pressed="${i===0}">${esc(v)}</button>`).join('')}</div>`;
 const gallery=(current.images?.length?current.images:[current.img]).map((url,i)=>`<img class="pd-photo ${i?'pd-extra':''}" loading="lazy" src="${esc(url)}" alt="${esc(current.name)} foto ${i+1}">`).join('');
 productDetail.innerHTML=`<div class="pd-scroll"><div class="pd-gallery">${gallery}</div><div class="pd-info"><p class="eyebrow">${esc(current.cat)}</p><h2>${esc(current.name)}</h2><div class="price-line"><span class="price">${CLP(current.price)}</span>${current.old?`<span class="old">${CLP(current.old)}</span>`:''}</div><p class="stock-state">${current.stock>0?'Disponible · '+current.stock+' unidades':'Agotado'}</p>${current.desc?`<details class="pd-description"><summary>Descripción y detalles</summary><p>${esc(current.desc)}</p></details>`:''}<strong>Talla</strong>${variants(current.sizes,'size')}<strong>Color</strong>${variants(current.colors,'color')}</div></div><div class="pd-actions"><button class="btn btn-wine" id="detailAddCart" ${current.stock<=0?'disabled':''}>${current.stock<=0?'Producto agotado':'Agregar al carrito'}</button><button class="wa" id="detailWhatsapp" ${current.stock<=0?'disabled':''}>Comprar por WhatsApp</button></div>`;
 productDetail.querySelector('#detailAddCart').onclick=addCart;productDetail.querySelector('#detailWhatsapp').onclick=directWhatsapp;productModal.classList.add('show');productDetail.querySelector('.pd-scroll').scrollTop=0;
};
renderCart=function(){if(!cart.length){cartList.innerHTML='<div class="empty">Tu carrito está vacío.</div>';cartTotal.textContent=CLP(0);return}cartList.innerHTML=cart.map((x,i)=>`<div class="cart-row"><img src="${escapeHtml(x.img)}"><div><strong>${escapeHtml(x.name)}</strong><div>${escapeHtml(x.size)} · ${escapeHtml(x.color)}</div><div class="qty"><button onclick="changeCartQty(${i},-1)">−</button><b>${x.qty}</b><button onclick="changeCartQty(${i},1)">+</button></div><div class="price">${CLP(x.price*x.qty)}</div></div><button class="icon-btn" onclick="removeCart(${i})">×</button></div>`).join('')+`<div class="checkout-fields"><input id="buyerName" placeholder="Tu nombre"><input id="buyerCommune" placeholder="Comuna o ciudad"><textarea id="buyerNotes" placeholder="Observaciones del pedido"></textarea></div>`;cartTotal.textContent=CLP(cart.reduce((sum,x)=>sum+x.price*x.qty,0))};
function changeCartQty(i,d){cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);save();renderCart()}
orderWhatsapp=function(){if(!cart.length)return toast('Tu carrito está vacío');const number=(activeBusiness?.whatsapp||'').replace(/\D/g,'');if(!number)return toast('El negocio aún no configuró WhatsApp');const name=document.querySelector('#buyerName')?.value.trim()||'Sin indicar',commune=document.querySelector('#buyerCommune')?.value.trim()||'Sin indicar',notes=document.querySelector('#buyerNotes')?.value.trim()||'Sin observaciones';const text=`Hola, quiero realizar este pedido en ${activeBusiness.name}:\n\n${cart.map(x=>`• ${x.name} | ${x.size} | ${x.color} | x${x.qty} | ${CLP(x.price*x.qty)}`).join('\n')}\n\nTotal: ${CLP(cart.reduce((s,x)=>s+x.price*x.qty,0))}\nCliente: ${name}\nComuna: ${commune}\nObservaciones: ${notes}`;window.open('https://wa.me/'+number+'?text='+encodeURIComponent(text),'_blank')};
const originalUploadCatalog=uploadImage;
uploadImage=async function(file){
 if(!file||!file.type.startsWith('image/'))return originalUploadCatalog(file);if(file.size<700000)return originalUploadCatalog(file);
 try{const bitmap=await createImageBitmap(file),max=1600,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.84));bitmap.close();if(blob)return originalUploadCatalog(new File([blob],file.name.replace(/\.[^.]+$/,'.webp'),{type:'image/webp'}))}catch(error){console.warn('Se usará la imagen original',error)}return originalUploadCatalog(file)
};
const originalRenderProfilesCatalog=renderProfiles;
renderProfiles=async function(){await originalRenderProfilesCatalog();const cards=[...adminContent.querySelectorAll('[data-panel=profiles] .admin-list .admin-card')];cards.forEach((card,i)=>{const member=(window.profileMembers||[])[i];if(!member)return;const controls=document.createElement('div');controls.className='access-controls';controls.innerHTML=`<label>Vencimiento de prueba <input type="date" value="${member.trial_ends_at?member.trial_ends_at.slice(0,10):''}"></label><button type="button">Guardar acceso</button><button type="button">Cambiar contraseña</button>`;controls.children[1].onclick=()=>manageMemberAccess(member.user_id,member.active,controls.querySelector('input').value);controls.children[2].onclick=()=>resetMemberPassword(member.user_id);card.appendChild(controls)})};
async function manageMemberAccess(userId,active,date){const {data,error}=await supabaseClient.functions.invoke('manage-business-admin',{body:{action:'access',userId,active,trialEndsAt:date?date+'T23:59:59Z':null}});if(error||data?.error)return toast(data?.error||error.message);toast('Acceso actualizado')}
async function resetMemberPassword(userId){const password=prompt('Escribe la nueva contraseña (mínimo 6 caracteres)');if(!password)return;if(password.length<6)return toast('La contraseña es demasiado corta');const {data,error}=await supabaseClient.functions.invoke('manage-business-admin',{body:{action:'password',userId,password}});if(error||data?.error)return toast(data?.error||error.message);toast('Contraseña actualizada')}
const productListWithQuickEdit=renderProductAdmin;
renderProductAdmin=async function(){await productListWithQuickEdit();const rows=[...document.querySelectorAll('#adminProductList .admin-product')];rows.forEach((row,i)=>{const p=adminProductsCache[i],details=document.createElement('details');details.className='quick-edit';details.innerHTML=`<summary>Edición rápida</summary><div class="quick-fields"><label>Precio <input type="number" min="0" value="${Number(p.price)}"></label><label>Stock <input type="number" min="0" value="${Number(p.stock||0)}"></label><label><input type="checkbox" ${p.active?'checked':''}> Visible</label><button>Guardar</button><button ${i===0?'disabled':''}>Subir</button><button ${i===rows.length-1?'disabled':''}>Bajar</button></div>`;const inputs=details.querySelectorAll('input'),buttons=details.querySelectorAll('button');buttons[0].onclick=()=>quickSaveProduct(p.id,inputs);buttons[1].onclick=()=>moveProduct(i,-1);buttons[2].onclick=()=>moveProduct(i,1);row.after(details)})};
async function quickSaveProduct(id,inputs){const {error}=await supabaseClient.from('products').update({price:Number(inputs[0].value||0),stock:Number(inputs[1].value||0),active:inputs[2].checked,updated_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message);toast('Cambios guardados');await renderProductAdmin();await loadStore()}
async function moveProduct(i,d){const other=i+d;if(other<0||other>=adminProductsCache.length)return;const a=adminProductsCache[i],b=adminProductsCache[other];await Promise.all([supabaseClient.from('products').update({sort_order:other}).eq('id',a.id),supabaseClient.from('products').update({sort_order:i}).eq('id',b.id)]);toast('Orden actualizado');await renderProductAdmin();await loadStore()}
