/* Menú público, perfil local del comprador y pedido multíproducto. */
(function customerExperience(){
 const safe=value=>typeof esc==='function'?esc(value):escapeHtml(value);
 const currentSlug=()=>activeBusiness?.slug||new URLSearchParams(location.search).get('tienda')||'tienda';
 const customerKey=()=>`tienda_ag_customer_${currentSlug()}`;
 const emptyCustomer=()=>({name:'',phone:'',address:'',commune:''});
 const readCustomer=()=>{try{return {...emptyCustomer(),...JSON.parse(localStorage.getItem(customerKey())||'{}')}}catch{return emptyCustomer()}};
 const cleanPhone=value=>String(value||'').replace(/\D/g,'');
 const validPhone=value=>{const digits=cleanPhone(value);return digits.length>=8&&digits.length<=15};
 const saveCustomer=data=>{try{localStorage.setItem(customerKey(),JSON.stringify(data));return true}catch{return false}};

 const style=document.createElement('style');
 style.textContent=`
 .store-menu-button{display:none;flex:0 0 auto;min-width:44px;min-height:44px;padding:8px 11px;font-size:1.35rem;line-height:1;color:var(--surface-text)!important;background:var(--surface)!important;border-color:var(--theme-line)!important}
 .store-menu-button.visible{display:inline-grid;place-items:center}.store-menu-backdrop{position:fixed;inset:0;z-index:79;background:#090b10a8;opacity:0;pointer-events:none;transition:opacity .2s ease}.store-menu-backdrop.show{opacity:1;pointer-events:auto}
 .store-menu-drawer{position:fixed;z-index:80;top:0;right:0;width:min(360px,90vw);height:100dvh;padding:calc(18px + env(safe-area-inset-top)) 16px calc(18px + env(safe-area-inset-bottom));overflow:auto;background:var(--surface);color:var(--surface-text);box-shadow:-20px 0 48px #07080b33;transform:translateX(105%);transition:transform .22s ease}.store-menu-drawer.show{transform:translateX(0)}
 .store-menu-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.store-menu-head strong{font-size:1.12rem}.store-menu-close{width:44px;height:44px;border:1px solid var(--theme-line);border-radius:50%;background:var(--surface-2);color:var(--surface-text);font-size:1.45rem}
 .store-menu-list{display:grid;gap:8px}.store-menu-item{min-height:50px;display:flex;align-items:center;gap:12px;width:100%;padding:12px 14px;border:1px solid var(--theme-line);border-radius:15px;background:var(--surface);color:var(--surface-text);font-weight:800;text-align:left}.store-menu-item:hover,.store-menu-item:focus-visible{background:var(--surface-2);outline:2px solid var(--theme-action);outline-offset:1px}.store-menu-item span{width:25px;text-align:center;font-size:1.1rem}.store-menu-admin{margin-top:10px;border-style:dashed}
 body.store-menu-open{overflow:hidden}.store-information{order:120;padding-top:14px;padding-bottom:36px}.store-information-grid{display:grid;gap:12px}.store-info-card{padding:18px;border:1px solid var(--theme-line);border-radius:20px;background:var(--surface);color:var(--surface-text);box-shadow:0 8px 24px #1214190d}.store-info-card h2,.store-info-card h3{margin:2px 0 10px;color:var(--surface-text)}.store-info-card h2{font-size:1.65rem}.store-info-card p{margin:0;color:var(--theme-muted);white-space:pre-line;line-height:1.65}.store-info-details{display:grid;gap:14px}.store-info-detail strong{display:block;margin-bottom:4px}.store-info-actions{margin-top:14px}
 .customer-profile-intro{margin:0 0 16px;color:var(--theme-muted);line-height:1.5}.customer-form{display:grid;gap:12px}.customer-form .btn{min-height:48px}.customer-privacy{margin:0;color:var(--theme-muted);font-size:.78rem;line-height:1.45}.checkout-fields{display:grid;gap:10px;margin-top:16px;padding:15px;border:1px solid var(--theme-line);border-radius:18px;background:var(--surface-2)}.checkout-fields h3{margin:0 0 2px}.checkout-fields input,.checkout-fields textarea{width:100%;padding:12px 13px;border:1px solid var(--theme-line);border-radius:12px;background:var(--surface);color:var(--surface-text)}.checkout-fields textarea{min-height:78px;resize:vertical}.checkout-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.continue-shopping{width:100%;margin-top:9px;min-height:46px}.cart-added-toast{white-space:normal;text-align:center}
 .cart-added-panel{position:fixed;z-index:75;left:50%;bottom:calc(82px + env(safe-area-inset-bottom));width:min(430px,calc(100% - 24px));padding:14px;border:1px solid var(--theme-line);border-radius:18px;background:var(--surface);color:var(--surface-text);box-shadow:0 18px 50px #090b103d;transform:translate(-50%,24px);opacity:0;pointer-events:none;transition:.2s ease}.cart-added-panel.show{transform:translate(-50%,0);opacity:1;pointer-events:auto}.cart-added-copy{display:flex;align-items:center;gap:10px;margin-bottom:11px}.cart-added-check{display:grid;place-items:center;flex:0 0 34px;width:34px;height:34px;border-radius:50%;background:#198754;color:#fff;font-weight:900}.cart-added-copy strong{display:block}.cart-added-copy small{display:block;margin-top:2px;color:var(--theme-muted)}.cart-added-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.cart-added-actions button{min-height:44px}.cart-bump{animation:cart-bump .4s ease}@keyframes cart-bump{50%{transform:scale(1.14)}}
 @media(min-width:700px){.store-information-grid{grid-template-columns:1.1fr .9fr}.store-info-card:only-child{grid-column:1/-1}.customer-sheet{max-width:520px!important}}
 @media(max-width:480px){.store-menu-button{padding:7px 8px}.topbar .top-actions{gap:3px}.checkout-actions{grid-template-columns:1fr}.store-info-card{padding:16px}}
 `;
 document.head.appendChild(style);

 let cartConfirmationTimer=0;
 function ensureCartConfirmation(){let panel=document.querySelector('#cartAddedPanel');if(panel)return panel;panel=document.createElement('section');panel.id='cartAddedPanel';panel.className='cart-added-panel';panel.setAttribute('role','status');panel.setAttribute('aria-live','polite');panel.innerHTML=`<div class="cart-added-copy"><span class="cart-added-check">✓</span><div><strong>Producto agregado al carrito</strong><small id="cartAddedProduct"></small></div></div><div class="cart-added-actions"><button class="btn btn-outline" type="button" id="cartKeepShopping">Seguir comprando</button><button class="btn btn-wine" type="button" id="cartViewNow">Ver carrito</button></div>`;panel.querySelector('#cartKeepShopping').onclick=hideCartConfirmation;panel.querySelector('#cartViewNow').onclick=()=>{hideCartConfirmation();openCart()};document.body.appendChild(panel);return panel}
 function hideCartConfirmation(){clearTimeout(cartConfirmationTimer);document.querySelector('#cartAddedPanel')?.classList.remove('show')}
 function showCartConfirmation(productName){const panel=ensureCartConfirmation();panel.querySelector('#cartAddedProduct').textContent=`${productName} · ${cart.reduce((sum,item)=>sum+Number(item.qty||0),0)} producto${cart.reduce((sum,item)=>sum+Number(item.qty||0),0)===1?'':'s'} en tu carrito`;panel.classList.add('show');const cartButton=document.querySelector('#cartTop');cartButton?.classList.remove('cart-bump');void cartButton?.offsetWidth;cartButton?.classList.add('cart-bump');clearTimeout(cartConfirmationTimer);cartConfirmationTimer=setTimeout(hideCartConfirmation,6500)}

 function ensureCustomerModal(){
  if(document.querySelector('#customerModal'))return;
  const modal=document.createElement('div');modal.className='modal';modal.id='customerModal';
  modal.innerHTML=`<div class="sheet customer-sheet"><button class="close" aria-label="Cerrar perfil de compra" onclick="closeModal('customerModal')">×</button><p class="eyebrow">Tus datos</p><h2 style="margin:4px 0 8px">Mi perfil de compra</h2><p class="customer-profile-intro">Completa tus datos una vez. Al confirmar un pedido se agregarán automáticamente al mensaje de WhatsApp.</p><form id="customerProfileForm" class="customer-form"><div class="field"><label for="customerName">Nombre y apellido</label><input id="customerName" name="name" autocomplete="name" placeholder="Ej. Andrea González" required></div><div class="field"><label for="customerPhone">Teléfono</label><input id="customerPhone" name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="Ej. +56 9 1234 5678" required></div><div class="field"><label for="customerAddress">Dirección</label><input id="customerAddress" name="address" autocomplete="street-address" placeholder="Ej. Calle, número y departamento"></div><div class="field"><label for="customerCommune">Comuna o ciudad</label><input id="customerCommune" name="commune" autocomplete="address-level2" placeholder="Ej. Santiago Centro"></div><p class="profile-message" id="customerProfileMessage" role="alert"></p><p class="customer-privacy">Estos datos quedan guardados únicamente en este dispositivo y se comparten con la tienda solo cuando tú envías el pedido.</p><button class="btn btn-wine" type="submit">Guardar mis datos</button></form></div>`;
  modal.addEventListener('click',event=>{if(event.target===modal)closeModal('customerModal')});document.body.appendChild(modal);
  modal.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,data={name:form.elements.name.value.trim(),phone:form.elements.phone.value.trim(),address:form.elements.address.value.trim(),commune:form.elements.commune.value.trim()},message=modal.querySelector('#customerProfileMessage');if(!data.name){message.textContent='Escribe tu nombre para guardar el perfil.';return}if(!validPhone(data.phone)){message.textContent='Escribe un teléfono válido de 8 a 15 dígitos.';return}if(!saveCustomer(data)){message.textContent='No fue posible guardar los datos en este dispositivo.';return}message.textContent='';closeModal('customerModal');toast('Perfil de compra guardado')});
 }
 window.openCustomerProfile=function(){
  closeStoreMenu();ensureCustomerModal();const data=readCustomer(),form=document.querySelector('#customerProfileForm');for(const field of ['name','phone','address','commune'])form.elements[field].value=data[field]||'';document.querySelector('#customerProfileMessage').textContent='';document.querySelector('#customerModal').classList.add('show');setTimeout(()=>form.elements.name.focus(),80);
 };

 function ensureStoreMenu(){
  let button=document.querySelector('#storeMenuBtn');
  if(!button){button=document.createElement('button');button.id='storeMenuBtn';button.className='icon-btn store-menu-button';button.type='button';button.innerHTML='☰';button.setAttribute('aria-label','Abrir menú de la tienda');button.setAttribute('aria-controls','storeMenuDrawer');button.setAttribute('aria-expanded','false');document.querySelector('.top-actions')?.append(button);button.addEventListener('click',openStoreMenu)}
  if(document.querySelector('#storeMenuDrawer'))return;
  const backdrop=document.createElement('div');backdrop.id='storeMenuBackdrop';backdrop.className='store-menu-backdrop';backdrop.addEventListener('click',closeStoreMenu);
  const drawer=document.createElement('aside');drawer.id='storeMenuDrawer';drawer.className='store-menu-drawer';drawer.setAttribute('aria-hidden','true');drawer.innerHTML=`<div class="store-menu-head"><strong id="storeMenuTitle">Menú de la tienda</strong><button class="store-menu-close" type="button" aria-label="Cerrar menú">×</button></div><nav class="store-menu-list" aria-label="Secciones de la tienda"><button class="store-menu-item" type="button" data-scroll="inicio"><span>⌂</span>Inicio</button><button class="store-menu-item" type="button" data-scroll="catalogo"><span>▦</span>Catálogo</button><button class="store-menu-item" id="aboutMenuItem" type="button" data-scroll="aboutStore"><span>ⓘ</span>Quiénes somos</button><button class="store-menu-item" id="contactMenuItem" type="button" data-scroll="contactStore"><span>⌖</span>Contacto y ubicación</button><button class="store-menu-item" type="button" data-action="profile"><span>☺</span>Mi perfil de compra</button><button class="store-menu-item" type="button" data-action="favorites"><span>♡</span>Favoritos</button><button class="store-menu-item" type="button" data-action="cart"><span>👜</span>Carrito</button><button class="store-menu-item store-menu-admin" type="button" data-action="admin"><span>⚙</span>Administración de la tienda</button></nav>`;
  drawer.querySelector('.store-menu-close').addEventListener('click',closeStoreMenu);drawer.addEventListener('click',event=>{const item=event.target.closest('.store-menu-item');if(!item)return;if(item.dataset.scroll){closeStoreMenu();document.getElementById(item.dataset.scroll)?.scrollIntoView({behavior:'smooth',block:'start'})}if(item.dataset.action==='profile')openCustomerProfile();if(item.dataset.action==='favorites'){closeStoreMenu();document.querySelector('#favNav')?.click()}if(item.dataset.action==='cart'){closeStoreMenu();openCart()}if(item.dataset.action==='admin'){closeStoreMenu();openProfile()}});
  document.body.append(backdrop,drawer);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeStoreMenu()});
 }
 window.openStoreMenu=function(){ensureStoreMenu();document.querySelector('#storeMenuBackdrop').classList.add('show');document.querySelector('#storeMenuDrawer').classList.add('show');document.querySelector('#storeMenuDrawer').setAttribute('aria-hidden','false');document.querySelector('#storeMenuBtn').setAttribute('aria-expanded','true');document.body.classList.add('store-menu-open');document.querySelector('.store-menu-close').focus()};
 window.closeStoreMenu=function(){document.querySelector('#storeMenuBackdrop')?.classList.remove('show');document.querySelector('#storeMenuDrawer')?.classList.remove('show');document.querySelector('#storeMenuDrawer')?.setAttribute('aria-hidden','true');document.querySelector('#storeMenuBtn')?.setAttribute('aria-expanded','false');document.body.classList.remove('store-menu-open')};

 function contactLink(label,url,type){if(!url)return '';return `<a class="btn btn-outline" data-contact="${safe(type)}" href="${safe(url)}" target="_blank" rel="noopener noreferrer">${safe(label)}</a>`}
 function renderStoreInformation(business){
  if(!business)return;const c={...brandDefaults,...business.customization};let section=document.querySelector('#storeLinks');if(!section){section=document.createElement('section');section.id='storeLinks';document.querySelector('main')?.appendChild(section)}section.className='section store-information';
  const phone=String(c.phone||'').replace(/[^+0-9]/g,''),wa=String(business.whatsapp||'').replace(/\D/g,''),details=[['Horarios',c.hours],['Entregas y pagos',c.delivery],['Dirección',business.address]].filter(([,value])=>String(value||'').trim());
  const links=[contactLink('Instagram',webUrl(business.instagram),'instagram'),contactLink('TikTok',webUrl(business.tiktok),'tiktok'),contactLink('Facebook',webUrl(c.facebook),'facebook'),contactLink('Cómo llegar',webUrl(c.maps),'como-llegar'),contactLink('Sitio web',webUrl(c.website),'sitio-web'),contactLink('WhatsApp',wa?'https://wa.me/'+wa:'','whatsapp'),contactLink('Llamar',phone?'tel:'+phone:'','llamar'),contactLink('Correo',/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.email)?'mailto:'+c.email:'','correo')].filter(Boolean);
  const about=String(c.about||'').trim();section.innerHTML=`<div class="store-information-grid">${about?`<article class="store-info-card" id="aboutStore"><p class="eyebrow">Conócenos</p><h2>Quiénes somos</h2><p>${safe(about)}</p></article>`:''}${details.length||links.length?`<article class="store-info-card" id="contactStore"><p class="eyebrow">Información útil</p><h2>Contacto y ubicación</h2>${details.length?`<div class="store-info-details">${details.map(([label,value])=>`<div class="store-info-detail"><strong>${safe(label)}</strong><p>${safe(value)}</p></div>`).join('')}</div>`:''}${links.length?`<div class="brand-contact store-info-actions">${links.join('')}</div>`:''}</article>`:''}</div>`;
  section.hidden=!about&&!details.length&&!links.length;document.querySelector('main')?.appendChild(section);
  ensureStoreMenu();document.querySelector('#storeMenuTitle').textContent=business.name;document.querySelector('#storeMenuBtn').classList.add('visible');document.querySelector('#aboutMenuItem').hidden=!about;document.querySelector('#contactMenuItem').hidden=!details.length&&!links.length;
  const profileNav=document.querySelector('#profileNav');if(profileNav){profileNav.innerHTML='<span>☺</span>Mi perfil';profileNav.setAttribute('aria-label','Abrir mi perfil de compra');profileNav.onclick=openCustomerProfile}
 }

 const originalApplyBusiness=applyBusiness;
 applyBusiness=function(business){originalApplyBusiness(business);renderStoreInformation(business)};

 addCart=function(){
  if(!current)return toast('Selecciona un producto');if(typeof selectedProductVariantAvailable==='function'&&!selectedProductVariantAvailable())return toast('Esta combinación está agotada');
  const {size:selectedSize,color:selectedColor}=selectedProductVariant(),key=current.id+'|'+selectedSize+'|'+selectedColor,row=cart.find(item=>item.key===key),imageIndex=variantOptionsOf(current).image_colors.findIndex(color=>normVariant(color)===normVariant(selectedColor)),image=current.images?.[imageIndex]||current.img;
  const productName=current.name;if(row)row.qty=Number(row.qty||0)+1;else cart.push({key,id:current.id,name:current.name,price:Number(current.price),img:image,size:selectedSize,color:selectedColor,qty:1});save();closeModal('productModal');showCartConfirmation(productName);
 };

 const originalRenderCart=renderCart;
 renderCart=function(){
  originalRenderCart();if(!cart.length)return;const data=readCustomer(),existing=document.querySelector('#cartList .checkout-fields');existing?.remove();const box=document.createElement('div');box.className='checkout-fields';box.innerHTML=`<h3>Datos para el pedido</h3><input id="buyerName" autocomplete="name" placeholder="Nombre y apellido" value="${safe(data.name)}"><input id="buyerPhone" type="tel" inputmode="tel" autocomplete="tel" placeholder="Teléfono" value="${safe(data.phone)}"><input id="buyerAddress" autocomplete="street-address" placeholder="Dirección" value="${safe(data.address)}"><input id="buyerCommune" autocomplete="address-level2" placeholder="Comuna o ciudad" value="${safe(data.commune)}"><textarea id="buyerNotes" placeholder="Observaciones del pedido"></textarea><div class="checkout-actions"><button class="btn btn-outline" type="button" id="saveCartCustomer">Guardar mis datos</button><button class="btn btn-outline" type="button" id="continueShopping">Seguir agregando</button></div>`;document.querySelector('#cartList').appendChild(box);box.querySelector('#saveCartCustomer').onclick=saveCustomerFromCart;box.querySelector('#continueShopping').onclick=continueShopping;
 };
 function customerFromCart(){return {name:document.querySelector('#buyerName')?.value.trim()||'',phone:document.querySelector('#buyerPhone')?.value.trim()||'',address:document.querySelector('#buyerAddress')?.value.trim()||'',commune:document.querySelector('#buyerCommune')?.value.trim()||'',notes:document.querySelector('#buyerNotes')?.value.trim()||''}}
 window.saveCustomerFromCart=function(){const data=customerFromCart();if(!data.name)return toast('Escribe tu nombre');if(!validPhone(data.phone))return toast('Escribe un teléfono válido');saveCustomer({name:data.name,phone:data.phone,address:data.address,commune:data.commune});toast('Datos guardados en este dispositivo')};
 window.continueShopping=function(){closeModal('cartModal');document.querySelector('#catalogo')?.scrollIntoView({behavior:'smooth',block:'start'})};

 buildWhatsappOrder=function(items,customer={}){
  const store=String(activeBusiness?.name||'la tienda').toLocaleUpperCase('es-CL'),productsText=items.map(item=>`${orderProductEmoji(item)} *${item.name}*\n• Talla: ${item.size||'Única'}\n• Color: ${item.color||'Consultar'}\n• Cantidad: ${Number(item.qty||1)}\n• Precio: ${CLP(Number(item.price||0)*Number(item.qty||1))}`).join('\n\n'),total=items.reduce((sum,item)=>sum+Number(item.price||0)*Number(item.qty||1),0);
  return `🛍️ *NUEVO PEDIDO — ${store}*\n\nHola 👋 Quiero realizar el siguiente pedido:\n\n━━━━━━━━━━━━━━\n🛒 *PRODUCTOS*\n\n${productsText}\n\n━━━━━━━━━━━━━━\n💰 *TOTAL: ${CLP(total)}*\n━━━━━━━━━━━━━━\n\n👤 *Cliente:* ${customer.name||'Sin indicar'}\n📱 *Teléfono:* ${customer.phone||'Sin indicar'}\n🏠 *Dirección:* ${customer.address||'Sin indicar'}\n📍 *Comuna o ciudad:* ${customer.commune||'Sin indicar'}\n📝 *Observaciones:* ${customer.notes||'Sin observaciones'}\n\n✅ Quedo atento/a a la confirmación de disponibilidad y coordinación del pedido. ¡Gracias!`;
 };
 orderWhatsapp=function(){if(!cart.length)return toast('Tu carrito está vacío');const number=String(activeBusiness?.whatsapp||'').replace(/\D/g,'');if(!number)return toast('El negocio aún no configuró WhatsApp');const customer=customerFromCart();if(!customer.name)return toast('Escribe tu nombre antes de enviar');if(!validPhone(customer.phone))return toast('Escribe un teléfono válido antes de enviar');saveCustomer({name:customer.name,phone:customer.phone,address:customer.address,commune:customer.commune});window.open('https://wa.me/'+number+'?text='+encodeURIComponent(buildWhatsappOrder(cart,customer)),'_blank','noopener')};
 directWhatsapp=function(){if(!current||!selectedProductVariantAvailable())return toast('Esta combinación está agotada');const customer=readCustomer();if(!customer.name||!validPhone(customer.phone)){openCustomerProfile();return toast('Completa tu perfil para enviar el pedido')}const {size,color}=selectedProductVariant(),number=String(activeBusiness?.whatsapp||'').replace(/\D/g,'');if(!number)return toast('El negocio aún no configuró WhatsApp');window.open('https://wa.me/'+number+'?text='+encodeURIComponent(buildWhatsappOrder([{...current,size,color,qty:1}],customer)),'_blank','noopener')};

 ensureCustomerModal();ensureStoreMenu();ensureCartConfirmation();
 if(activeBusiness)renderStoreInformation(activeBusiness);
})();
