/* Tienda AG: theme coherence and advanced catalog/admin improvements. */
const bmEnhancementStyle=document.createElement('style');
bmEnhancementStyle.textContent=`
:root{--theme-soft:color-mix(in srgb,var(--wine) 9%,white);--theme-line:color-mix(in srgb,var(--wine) 18%,white)}
body{background:linear-gradient(180deg,var(--brand-bg),#fff 58%,var(--theme-soft))}.topbar{background:color-mix(in srgb,var(--brand-bg) 91%,transparent)!important;border-color:var(--theme-line)!important}.bottom{background:color-mix(in srgb,var(--brand-bg) 94%,white)!important;border-color:var(--theme-line)!important}.icon-btn,.card,.promo,.category-card{border-color:var(--theme-line)!important}.category-card{background:linear-gradient(150deg,#fff,var(--theme-soft))!important}.category-card.active{background:linear-gradient(145deg,var(--wine),var(--wine2))!important;color:#fff!important}.nav.active,.brand,.promo strong,.card-body .cat,.quick{color:var(--wine)!important}
.topbar{gap:7px}.topbar .brand-identity{flex:1 1 auto;min-width:0;max-width:none!important}.topbar .brand-copy{flex:1 1 auto;min-width:0;overflow:visible!important}.topbar .top-actions{flex:0 0 auto}.topbar .brand-copy .brand{font-size:clamp(.95rem,4vw,1.35rem);line-height:1.08;white-space:normal!important;overflow:visible!important;text-overflow:clip!important;display:block!important;-webkit-line-clamp:unset!important}.topbar .brand-copy .brand-kicker{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.topbar.is-compact .brand-copy .brand{font-size:clamp(.82rem,3.7vw,1.02rem);line-height:1!important;white-space:nowrap!important;display:block!important;overflow:visible!important;text-overflow:clip!important}.topbar.is-compact .brand-identity{max-width:none!important}
main.store-sections{display:flex;flex-direction:column}.catalog-tools{display:flex;gap:8px;align-items:center}.catalog-sort{border:1px solid var(--theme-line);border-radius:12px;background:#fff;color:var(--ink);padding:8px 28px 8px 10px;max-width:165px}.filters{grid-template-columns:repeat(2,minmax(0,1fr))}.filter-chips{display:flex;flex-wrap:wrap;gap:7px;margin:-2px 0 14px}.active-filter{border:0;border-radius:999px;padding:7px 10px;background:var(--theme-soft);color:var(--wine);font-size:.75rem;font-weight:800}.clear-filters{background:var(--wine);color:#fff}.related-products,.recent-products{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.related-product,.recent-product{border:1px solid var(--theme-line);border-radius:14px;background:#fff;padding:7px;text-align:left;color:var(--ink)}.related-product img,.recent-product img{width:100%;aspect-ratio:4/5;object-fit:cover;object-position:var(--focus,50% 50%);border-radius:10px}.related-product strong,.recent-product strong{display:block;margin-top:6px;font-size:.76rem}.related-heading{margin:24px 0 10px!important}.share-product{background:#fff!important;color:var(--wine)!important;border:1px solid var(--theme-line)!important}.recent-section{padding-top:10px}.section-setting{display:grid;grid-template-columns:1fr 72px;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid var(--line)}.section-setting:last-child{border:0}.section-setting input[type=number]{width:70px;padding:8px;border:1px solid var(--line);border-radius:9px}.focus-controls label{display:grid;grid-template-columns:1fr auto;gap:6px;color:var(--muted);font-size:.82rem;font-weight:800}.focus-controls input{grid-column:1/-1;width:100%;accent-color:var(--wine)}.publication-card select,.publication-card input[type=datetime-local]{width:100%;border:1px solid var(--line);border-radius:12px;padding:11px;background:#fff}.admin-product[draggable=true]{cursor:grab}.admin-product.dragging{opacity:.45}.admin-product.drag-over{outline:3px solid var(--wine);outline-offset:2px}.drag-hint{font-size:.72rem;color:var(--muted);margin:0 0 8px}.product-link-note{font-size:.75rem;color:var(--muted);margin:7px 0 0;word-break:break-all}
.icon-btn,.quick,.nav,.chip,.filter-btn,.catalog-sort,.filters select,.active-filter,.pd-thumb,.contact-button,.small-actions button{min-height:44px}.store-action-row a{text-decoration:none}.portal-mark{color:transparent!important;background:#0b0b0c url('/assets/icons/tienda-ag-logo.svg') center/82% no-repeat!important}.offline-notice{position:fixed;z-index:95;top:max(8px,env(safe-area-inset-top));left:50%;transform:translateX(-50%);padding:9px 13px;border-radius:999px;background:#111;color:#fff;font-size:.78rem;font-weight:800;box-shadow:0 8px 24px #0003}.swipe-hint{text-align:center;color:var(--muted);font-size:.76rem;margin:8px 0 0}@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
@media(max-width:480px){.topbar{padding-left:9px;padding-right:9px}.brand-identity{gap:6px;max-width:none!important}.brand-identity .brand-logo{width:40px!important;height:40px!important;max-width:40px!important;max-height:40px!important}.top-actions{gap:4px}.icon-btn{min-width:44px;padding:7px 8px}.brand-copy .brand-kicker{display:none}.filters{grid-template-columns:1fr}.catalog-sort{max-width:142px;font-size:.74rem}.pd-actions{grid-template-columns:1fr 1fr}.pd-actions .share-product{grid-column:1/-1}.related-products{grid-template-columns:repeat(3,minmax(0,1fr))}.related-product strong{font-size:.64rem}.topbar.is-compact .brand-identity{max-width:none!important}.topbar.is-compact .brand-logo{width:34px!important;height:34px!important;max-width:34px!important;max-height:34px!important}.topbar.is-compact .icon-btn{min-width:44px;padding:6px 7px}}
`;
document.head.appendChild(bmEnhancementStyle);

for(const [key,value] of Object.entries({show_hero:'on',show_contacts:'on',show_categories:'on',show_catalog:'on',show_recent:'on',home_order_hero:'1',home_order_contacts:'2',home_order_promos:'3',home_order_categories:'4',home_order_recent:'5',home_order_catalog:'6'}))if(!(key in brandDefaults))brandDefaults[key]=value;

function bmThemeMeta(){
 const safe='#111111';
 let theme=document.querySelector('meta[name="theme-color"]');if(!theme){theme=document.createElement('meta');theme.name='theme-color';document.head.append(theme)}theme.content=safe;
 for(const name of ['msapplication-navbutton-color','apple-mobile-web-app-status-bar-style']){let meta=document.querySelector(`meta[name="${name}"]`);if(!meta){meta=document.createElement('meta');meta.name=name;document.head.append(meta)}meta.content=name==='apple-mobile-web-app-status-bar-style'?'black':safe}
 document.documentElement.style.setProperty('--system-bar-color',safe);
}
bmThemeMeta();
const bmSetThemeColor=setThemeColor;setThemeColor=function(){bmSetThemeColor();bmThemeMeta()};

function fitBrandName(){
 const topbar=document.querySelector('.topbar'),brand=topbar?.querySelector('.brand'),copy=topbar?.querySelector('.brand-copy');if(!topbar||!brand||!copy)return;
 brand.style.removeProperty('font-size');brand.style.whiteSpace='nowrap';
 const available=copy.clientWidth;if(!available)return;
 let size=topbar.classList.contains('is-compact')?16:21,min=topbar.classList.contains('is-compact')?12:14;
 brand.style.fontSize=size+'px';while(brand.scrollWidth>available&&size>min){size-=.5;brand.style.fontSize=size+'px'}
 if(brand.scrollWidth>available&&!topbar.classList.contains('is-compact'))brand.style.whiteSpace='normal';
}
function bmFitBrandSoon(){if(typeof requestAnimationFrame==='function')requestAnimationFrame(fitBrandName);else setTimeout(fitBrandName,0)}
window.addEventListener('scroll',bmFitBrandSoon,{passive:true});window.addEventListener('resize',fitBrandName);document.fonts?.ready.then(fitBrandName);

const bmApplyBusiness=applyBusiness;
applyBusiness=function(b){bmApplyBusiness(b);const primary=colorValue(b.primary_color,'#772640');bmThemeMeta();document.documentElement.style.setProperty('--theme-primary',primary);applyHomeSections(b);bmFitBrandSoon();setTimeout(fitBrandName,120)};

function bmEnabled(value){return value!==false&&value!=='false'&&value!==''&&value!=='off'}
function applyHomeSections(business){
 const main=document.querySelector('main');if(!main||!business)return;main.classList.add('store-sections');const c={...brandDefaults,...business.customization},categories=document.querySelector('#categories')?.closest('.section');
 const items=[['hero',document.querySelector('.hero'),c.show_hero],['contacts',document.querySelector('#storeActions'),c.show_contacts],['promos',document.querySelector('.promo-row'),c.show_promos],['categories',categories,c.show_categories],['recent',document.querySelector('#recentlyViewed'),c.show_recent],['catalog',document.querySelector('#catalogo'),c.show_catalog]];
 items.forEach(([key,element,visible])=>{if(!element)return;element.style.order=String(Number(c['home_order_'+key])||99);element.hidden=!bmEnabled(visible);if(!bmEnabled(visible))element.style.display='none';else if(key!=='promos'||c.show_promos!==false)element.style.removeProperty('display')});
}

function productUrl(product=current){const url=new URL(location.href);url.searchParams.set('tienda',activeBusiness?.slug||url.searchParams.get('tienda')||'');url.searchParams.set('producto',product?.id||'');return url.href}
async function shareCurrentProduct(){
 if(!current)return;const data={title:current.name,text:`${current.name} · ${CLP(current.price)} en ${activeBusiness?.name||'la tienda'}`,url:productUrl(current)};
 try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast('Link del producto copiado')}}catch(error){if(error?.name!=='AbortError')toast('No se pudo compartir el producto')}
}
function rememberProduct(product){
 try{const key='bm_recent_'+(activeBusiness?.slug||'tienda'),ids=JSON.parse(localStorage.getItem(key)||'[]').filter(id=>id!==product.id);ids.unshift(product.id);localStorage.setItem(key,JSON.stringify(ids.slice(0,8)))}catch{}renderRecentlyViewed();
}
function renderRecentlyViewed(){
 if(!activeBusiness)return;let section=document.querySelector('#recentlyViewed');if(!section){section=document.createElement('section');section.id='recentlyViewed';section.className='section recent-section';document.querySelector('#catalogo')?.before(section)}let ids=[];try{ids=JSON.parse(localStorage.getItem('bm_recent_'+activeBusiness.slug)||'[]')}catch{}const rows=ids.map(id=>products.find(p=>String(p.id)===String(id))).filter(Boolean).slice(0,4);section.innerHTML=rows.length?`<div class="heading"><div><p class="eyebrow">Para volver a mirar</p><h2>Vistos recientemente</h2></div></div><div class="recent-products">${rows.map(p=>`<button class="recent-product" onclick="openProduct('${p.id}')" style="--focus:${p.variant_options?.focus?.x||50}% ${p.variant_options?.focus?.y||50}%"><img src="${esc(p.img)}" alt="${esc(p.name)}"><strong>${esc(p.name)}</strong><span class="price">${CLP(p.price)}</span></button>`).join('')}</div>`:'';applyHomeSections(activeBusiness)
}

const bmOpenProduct=openProduct;
openProduct=function(id,options={}){
 bmOpenProduct(id);if(!current)return;rememberProduct(current);const url=new URL(location.href);url.searchParams.set('producto',current.id);if(!options.fromUrl)history.pushState({producto:current.id},'',url);
 const actions=productDetail.querySelector('.pd-actions');if(actions&&!actions.querySelector('.share-product')){const share=document.createElement('button');share.type='button';share.className='btn share-product';share.textContent='Compartir producto';share.onclick=shareCurrentProduct;actions.append(share)}
 const info=productDetail.querySelector('.pd-info'),related=products.filter(p=>p.id!==current.id&&p.cat===current.cat).slice(0,3);if(info&&related.length){info.insertAdjacentHTML('beforeend',`<h3 class="related-heading">También te puede gustar</h3><div class="related-products">${related.map(p=>`<button class="related-product" type="button" onclick="openProduct('${p.id}')" style="--focus:${p.variant_options?.focus?.x||50}% ${p.variant_options?.focus?.y||50}%"><img src="${esc(p.img)}" alt="${esc(p.name)}"><strong>${esc(p.name)}</strong><span class="price">${CLP(p.price)}</span></button>`).join('')}</div>`)}
};
const bmCloseModal=closeModal;closeModal=function(id){bmCloseModal(id);if(id==='productModal'&&new URLSearchParams(location.search).has('producto')){const url=new URL(location.href);url.searchParams.delete('producto');history.replaceState({},'',url)}};
window.addEventListener('popstate',()=>{const id=new URLSearchParams(location.search).get('producto');if(id&&products.some(p=>String(p.id)===id))openProduct(id,{fromUrl:true});else bmCloseModal('productModal')});

let bmSort='featured',bmColor='',bmAvailability='';
function ensureCatalogControls(){
 const meta=document.querySelector('#catalogo .meta'),filters=document.querySelector('#filters');if(!meta||!filters)return;if(!document.querySelector('#catalogSort')){meta.lastElementChild.innerHTML='<label class="catalog-tools"><span>Ordenar</span><select id="catalogSort" class="catalog-sort"><option value="featured">Destacados</option><option value="newest">Más nuevos</option><option value="price-asc">Menor precio</option><option value="price-desc">Mayor precio</option><option value="name">Nombre A–Z</option></select></label>';document.querySelector('#catalogSort').onchange=e=>{bmSort=e.target.value;render()}}
 if(!document.querySelector('#colorFilter')){const color=document.createElement('select');color.id='colorFilter';color.setAttribute('aria-label','Filtrar por color');const availability=document.createElement('select');availability.id='availabilityFilter';availability.innerHTML='<option value="">Disponibles y agotados</option><option value="available">Solo disponibles</option><option value="sold_out">Solo agotados</option>';filters.append(color,availability);color.onchange=e=>{bmColor=e.target.value;render()};availability.onchange=e=>{bmAvailability=e.target.value;render()}}
 let chips=document.querySelector('#activeFilters');if(!chips){chips=document.createElement('div');chips.id='activeFilters';chips.className='filter-chips';filters.after(chips)}
}
function updateCatalogFilters(){const color=document.querySelector('#colorFilter');if(color){const selected=color.value,values=[...new Set(products.flatMap(p=>p.colors||[]))].sort((a,b)=>a.localeCompare(b,'es'));color.innerHTML='<option value="">Todos los colores</option>'+values.map(v=>`<option ${v===selected?'selected':''}>${esc(v)}</option>`).join('')}const chips=document.querySelector('#activeFilters');if(!chips)return;const active=[];if(selectedCat!=='Todas')active.push(['Categoría: '+selectedCat,()=>setCat('Todas')]);if(search.value)active.push(['Búsqueda: '+search.value,()=>{search.value='';render()}]);if(size.value)active.push(['Talla: '+size.value,()=>{size.value='';render()}]);if(priceFilter.value)active.push(['Precio seleccionado',()=>{priceFilter.value='';render()}]);if(bmColor)active.push(['Color: '+bmColor,()=>{bmColor='';document.querySelector('#colorFilter').value='';render()}]);if(bmAvailability)active.push([bmAvailability==='available'?'Disponibles':'Agotados',()=>{bmAvailability='';document.querySelector('#availabilityFilter').value='';render()}]);chips.replaceChildren(...active.map(([label,action])=>{const button=document.createElement('button');button.className='active-filter';button.textContent=label+' ×';button.onclick=action;return button}));if(active.length){const clear=document.createElement('button');clear.className='active-filter clear-filters';clear.textContent='Limpiar todo';clear.onclick=()=>{selectedCat='Todas';search.value='';size.value='';priceFilter.value='';bmColor='';bmAvailability='';document.querySelector('#colorFilter').value='';document.querySelector('#availabilityFilter').value='';renderCats();render()};chips.append(clear)}}
function bmCard(product){const sold=product.availability==='sold_out',photoCount=product.images?.length||1,focus=product.variant_options?.focus||{x:50,y:50};return `<article class="card"><div class="photo" onclick="openProduct('${product.id}')"><img loading="lazy" decoding="async" style="object-position:${focus.x}% ${focus.y}%" src="${escapeHtml(product.img)}" alt="${escapeHtml(product.name)}">${product.old?'<span class="sale">OFERTA</span>':''}${sold?'<span class="sale sold">AGOTADO</span>':''}<button class="heart" aria-label="Favorito" onclick="event.stopPropagation();toggleFav('${product.id}')">${favs.includes(product.id)?'♥':'♡'}</button>${photoCount>1?`<span class="photo-count">▣ ${photoCount}</span>`:''}<span class="availability-badge ${sold?'sold-out':''}">${sold?'Agotado':'Disponible'}</span></div><div class="card-body"><span class="cat">${escapeHtml(product.cat)}</span><h3>${escapeHtml(product.name)}</h3><div class="price-line"><span class="price">${CLP(product.price)}</span>${product.old?`<span class="old">${CLP(product.old)}</span>`:''}</div><button class="quick" onclick="openProduct('${product.id}')">Ver producto</button></div></article>`}
render=function(){ensureCatalogControls();const q=search.value.toLocaleLowerCase('es-CL'),s=size.value,p=Number(priceFilter.value||0);let rows=products.filter(x=>(selectedCat==='Todas'||x.cat===selectedCat)&&(!q||(x.name+' '+x.cat+' '+(x.desc||'')).toLocaleLowerCase('es-CL').includes(q))&&(!s||x.sizes.includes(s))&&(!p||x.price<=p)&&(!bmColor||x.colors.includes(bmColor))&&(!bmAvailability||x.availability===bmAvailability));rows=[...rows].sort((a,b)=>bmSort==='newest'?String(b.created_at).localeCompare(String(a.created_at)):bmSort==='price-asc'?a.price-b.price:bmSort==='price-desc'?b.price-a.price:bmSort==='name'?a.name.localeCompare(b.name,'es'):a.sort_order-b.sort_order);count.textContent=rows.length+' productos';grid.innerHTML=rows.map(bmCard).join('')||'<div class="empty" style="grid-column:1/-1">No encontramos productos con esos filtros.</div>';updateCatalogFilters()};

const bmLoadStore=loadStore;loadStore=async function(){await bmLoadStore();if(!activeBusiness)return;ensureCatalogControls();renderRecentlyViewed();render();applyHomeSections(activeBusiness);const productId=new URLSearchParams(location.search).get('producto');if(productId&&products.some(p=>String(p.id)===productId)&&!productModal.classList.contains('show'))openProduct(productId,{fromUrl:true})};

const bmRenderSettings=renderSettings;renderSettings=function(){bmRenderSettings();const form=document.querySelector('#settingsForm');if(!form||form.querySelector('.home-sections-card'))return;const c={...brandDefaults,...managedBusiness.customization},card=document.createElement('section');card.className='admin-card home-sections-card';const items=[['hero','Portada'],['contacts','Botones de contacto'],['promos','Avisos destacados'],['categories','Categorías'],['recent','Vistos recientemente'],['catalog','Catálogo']];card.innerHTML='<h3>Orden de la página</h3><p class="help-copy">Elige qué bloques aparecen y en qué orden.</p>'+items.map(([key,label],i)=>`<label class="section-setting"><span><input type="checkbox" name="show_${key}" ${bmEnabled(c['show_'+key])?'checked':''}> ${label}</span><input type="number" min="1" max="6" name="home_order_${key}" value="${Number(c['home_order_'+key])||i+1}" aria-label="Orden de ${label}"></label>`).join('');const visibility=[...form.querySelectorAll('.admin-card')].find(el=>el.textContent.includes('Visibilidad'));visibility?.before(card);const current=String(managedBusiness.primary_color||'').toLowerCase(),preset=palettePresets.find(item=>item.colors[0].toLowerCase()===current);if(preset){[...form.querySelectorAll('.palette-choice')].find(button=>button.textContent.trim()===preset.name)?.setAttribute('aria-pressed','true')}};

function enhanceAdminDrag(list,kind){if(!list)return;const rows=[...list.querySelectorAll(kind==='product'?'.admin-product':'.category-row')];rows.forEach((row,index)=>{row.draggable=true;row.dataset.dragIndex=index;row.ondragstart=()=>row.classList.add('dragging');row.ondragend=()=>row.classList.remove('dragging');row.ondragover=e=>{e.preventDefault();row.classList.add('drag-over')};row.ondragleave=()=>row.classList.remove('drag-over');row.ondrop=async e=>{e.preventDefault();row.classList.remove('drag-over');const from=Number(list.querySelector('.dragging')?.dataset.dragIndex),to=Number(row.dataset.dragIndex);if(!Number.isInteger(from)||from===to)return;const data=kind==='product'?adminProductsCache:adminCategories,item=data.splice(from,1)[0];data.splice(to,0,item);await Promise.all(data.map((entry,i)=>supabaseClient.from(kind==='product'?'products':'categories').update({sort_order:i}).eq('id',entry.id)));toast('Orden actualizado');kind==='product'?await renderProductAdmin():await renderCategoryAdmin();await loadStore()}})}
const bmRenderProductAdmin=renderProductAdmin;renderProductAdmin=async function(){await bmRenderProductAdmin();const list=document.querySelector('#adminProductList');if(list){list.insertAdjacentHTML('beforebegin','<p class="drag-hint">Mantén presionado y arrastra un producto para cambiar su orden. También puedes usar Subir/Bajar.</p>');enhanceAdminDrag(list,'product');list.querySelectorAll('.admin-product').forEach((row,i)=>{const p=adminProductsCache[i],state=variantOptionsOf(p).publication;row.querySelector('small')?.insertAdjacentText('afterbegin',(state==='draft'?'Borrador · ':state==='scheduled'?'Programado · ':''));row.querySelector('.small-actions')?.insertAdjacentHTML('beforeend',`<button type="button" onclick="navigator.clipboard.writeText('${esc(appBaseUrl+'?tienda='+(managedBusiness?.slug||'')+'&producto='+p.id)}').then(()=>toast('Link copiado'))">Copiar link</button>`)})}};
const bmRenderCategoryAdmin=renderCategoryAdmin;renderCategoryAdmin=async function(){await bmRenderCategoryAdmin();const list=document.querySelector('[data-panel=categories] .admin-list');if(list){list.insertAdjacentHTML('beforebegin','<p class="drag-hint">Arrastra las categorías para cambiar el orden.</p>');enhanceAdminDrag(list,'category')}};
