/* BellaMujer v7: portal, product availability, three-photo gallery and page management. */
const v7ApplyBusiness=applyBusiness;
const v7RenderSettings=renderSettings;

const v7Style=document.createElement('style');
v7Style.textContent=`
body.portal-mode{background:#f7f7f8;color:#25242a}body.portal-mode .topbar{background:rgba(255,255,255,.94);border-color:#e8e8ec}body.portal-mode .brand{font-family:Inter,system-ui,sans-serif!important;color:#24232a;font-size:1.35rem}body.portal-mode .brand-kicker{color:#76727d}body.portal-mode #brandLogo,body.portal-mode .top-actions{display:none!important}body.portal-mode .shell{max-width:1160px;padding-bottom:84px}body.portal-mode main>:not(#portalHome){display:none!important}body.portal-mode .bottom .nav:not(#profileNav){display:none}body.portal-mode .bottom{display:flex;justify-content:center}body.portal-mode #profileNav{min-width:180px}.portal-login{display:grid;gap:12px;justify-items:center}.portal-login .btn{min-width:220px}.portal-admin-actions{display:flex;justify-content:center;margin:0 0 24px}
.brand-identity{display:flex;align-items:center;gap:10px;min-width:0}.brand-copy{min-width:0}.brand-identity .brand-logo{flex:0 0 auto;width:46px!important;height:46px!important;max-width:46px!important;max-height:46px!important;margin:0!important;padding:3px;object-fit:contain;border-radius:12px;background:#fff;box-shadow:0 4px 14px #00000012}.brand-copy .brand,.brand-copy .brand-kicker{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.topbar{transition:padding .2s ease,box-shadow .2s ease}.topbar.is-compact{padding-top:7px;padding-bottom:7px;box-shadow:0 7px 20px #0000000f}.topbar.is-compact .brand-logo{width:34px!important;height:34px!important;max-width:34px!important;max-height:34px!important;border-radius:9px}.topbar.is-compact .brand-kicker{display:none}.topbar.is-compact .brand{font-size:1.18rem}.topbar.is-compact .icon-btn{padding:7px 9px;border-radius:12px}
.portal-home{padding:54px 18px 110px}.portal-intro{max-width:680px;margin:0 auto 34px;text-align:center}.portal-intro .portal-mark{width:58px;height:58px;display:grid;place-items:center;margin:0 auto 18px;border-radius:18px;background:#24232a;color:#fff;font-size:1.6rem}.portal-intro h2{font:700 clamp(2rem,7vw,3.6rem)/1.05 Inter,system-ui,sans-serif!important;margin:0 0 13px}.portal-intro p{color:#716d78;line-height:1.65;margin:0}.portal-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:18px}.portal-card{display:block;overflow:hidden;border:1px solid #e5e4e8;border-radius:22px;background:#fff;color:#25242a;text-decoration:none;box-shadow:0 10px 32px #2321280a;transition:.2s}.portal-card:hover{transform:translateY(-3px);box-shadow:0 16px 38px #23212816}.portal-cover{height:185px;background:linear-gradient(135deg,#eeeef1,#fafafa);position:relative;overflow:hidden}.portal-cover>img{width:100%;height:100%;object-fit:cover}.portal-logo{position:absolute;left:16px;bottom:14px;width:58px!important;height:58px!important;object-fit:contain!important;border-radius:16px;background:#fff;padding:7px;box-shadow:0 7px 22px #0002}.portal-card-body{padding:18px}.portal-card-body h3{font:800 1.2rem Inter,system-ui,sans-serif!important;margin:0 0 7px}.portal-card-body span{color:#6f6c75;font-size:.86rem}.portal-open{float:right;color:#24232a!important;font-weight:800}.portal-empty{max-width:560px;margin:auto;padding:36px;text-align:center;background:#fff;border:1px solid #e5e4e8;border-radius:22px;color:#716d78}
#storeActions{padding:6px 16px 16px}.store-action-row{display:flex;flex-wrap:wrap;justify-content:center;align-items:stretch;gap:10px;max-width:780px;margin:0 auto;padding:3px 0 8px;overflow:visible}.store-action-row .contact-button{display:inline-flex;align-items:center;justify-content:center;flex:0 1 158px;min-width:138px;gap:9px;white-space:nowrap;padding:12px 16px;border:1px solid transparent;border-radius:16px;font-size:.84rem;font-weight:850;background:#fff;box-shadow:0 7px 18px #2d202716;transition:transform .18s ease,box-shadow .18s ease}.store-action-row .contact-button:hover{transform:translateY(-2px);box-shadow:0 10px 22px #2d202724}.contact-icon{display:grid;place-items:center;width:24px;height:24px;color:inherit}.contact-icon svg{width:24px;height:24px;display:block}.contact-button[data-contact=whatsapp]{background:#25d366;color:#fff;border-color:#1fbd59}.contact-button[data-contact=instagram]{background:linear-gradient(135deg,#6c35b5 0%,#b52c82 52%,#e44b68 100%);color:#fff}.contact-button[data-contact=tiktok]{background:linear-gradient(135deg,#151515 0%,#252525 70%,#142f31 100%);color:#fff;border-color:#2f2f2f}.contact-button[data-contact=facebook]{background:#1877f2;color:#fff;border-color:#1167d6}.contact-button[data-contact=llamar]{background:#e7f8ee;color:#147a42;border-color:#b6e7c9}.contact-button[data-contact=como-llegar]{background:#eef4ff;color:#245cb5;border-color:#cadcff}.contact-button[data-contact=sitio-web]{background:#f7edf1;color:var(--wine);border-color:#ead2dc}.contact-button[data-contact=correo]{background:#fff4e8;color:#9a5315;border-color:#f1d4b2}.store-action-row:empty{display:none}#storeLinks{padding-top:18px}.promo-row{gap:7px}.promo{min-height:66px;padding:7px 8px;border-radius:14px;grid-template-columns:20px 1fr}.promo strong{font-size:.71rem}.promo small{font-size:.61rem}.promo span{font-size:.9rem}
.category-strip{grid-auto-columns:35%;gap:8px}.category-card{min-height:78px;border-radius:16px;padding:10px 11px}.cat-icon{font-size:1.15rem;margin-bottom:7px}.category-card strong{font-size:.82rem!important}.photo-count{position:absolute;right:9px;bottom:9px;background:#211d20cc;color:#fff;border-radius:999px;padding:5px 8px;font-size:.68rem;font-weight:900}.availability-badge{position:absolute;left:9px;bottom:9px;background:#fff;color:#18733c;border-radius:999px;padding:5px 8px;font-size:.65rem;font-weight:900;box-shadow:0 4px 12px #0001}.availability-badge.sold-out{color:#fff;background:#5b5860}.sale.sold{top:10px;background:#5b5860}.sale+.sale.sold{top:42px}
.image-field-simple{position:relative}.image-field-simple .image-preview{margin:8px 0}.image-tools{display:flex;gap:8px;align-items:center;margin-top:8px}.image-tools button{border:1px solid var(--line);background:#fff;border-radius:10px;padding:8px 10px;color:#a12648}.product-photo-slots{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.product-photo-slot{border:1px dashed #cfc7cc;border-radius:14px;padding:8px;min-width:0}.product-photo-slot img{width:100%;aspect-ratio:4/5;object-fit:cover;border-radius:10px;background:#f4eff2}.product-photo-slot label{display:block;text-align:center;font-size:.72rem;font-weight:800;margin:7px 0 4px}.product-photo-slot input[type=file]{width:100%;font-size:.68rem}.slot-remove{width:100%;border:0;background:#fff0f3;color:#a12648;border-radius:9px;padding:7px;margin-top:6px;font-size:.72rem;font-weight:800}.availability-select{font-weight:800}.admin-business-card{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center}.admin-business-card .small-actions{grid-column:1/-1;flex-wrap:wrap}.business-danger{margin-left:auto!important}
.photo-color-field{margin-top:8px!important}.photo-color-field input{width:100%;padding:9px;border:1px solid var(--line);border-radius:9px;font-size:.78rem}.variant-matrix{display:grid;gap:8px;margin-top:12px}.variant-row{display:grid;grid-template-columns:minmax(90px,1fr) repeat(var(--variant-cols,1),minmax(72px,1fr));gap:7px;align-items:center}.variant-row>strong{font-size:.82rem}.variant-cell{display:grid;place-items:center;gap:3px;min-height:54px;padding:7px;border:1px solid var(--line);border-radius:11px;background:#fff;font-size:.72rem;text-align:center}.variant-cell input{width:19px;height:19px;accent-color:var(--wine)}.variant-head{font-size:.72rem;font-weight:850;text-align:center;color:var(--muted)}.variant-summary{margin:10px 0 0;color:var(--muted);font-size:.78rem}.chip.variant-sold{opacity:.56;text-decoration:line-through}.chip:disabled{cursor:not-allowed}.color-chip{display:inline-flex;align-items:center;gap:7px}.color-dot{width:14px;height:14px;border-radius:50%;background:var(--swatch,#ddd);border:1px solid #0002;box-shadow:inset 0 0 0 1px #fff8}.pd-thumb{position:relative}.pd-thumb-label{position:absolute;left:2px;right:2px;bottom:2px;padding:2px;border-radius:5px;background:#111b;color:#fff;font-size:.52rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
#productModal{align-items:stretch!important;justify-content:center!important;background:#fff}#productModal>.sheet{width:100%!important;max-width:1040px!important;height:100dvh!important;max-height:100dvh!important;border-radius:0!important}#productModal>.sheet>.close{position:fixed;right:14px;top:14px;z-index:78;background:#ffffffe8;box-shadow:0 5px 18px #0002}#productModal .pd-scroll{display:block!important;padding:0!important}.pd-layout{display:grid;min-height:0}.pd-gallery-wrap{background:#f6f3f5;padding:52px 12px 14px;min-width:0}.pd-main-track{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;border-radius:18px}.pd-main-button{border:0;background:transparent;padding:0;min-width:100%;scroll-snap-align:center}.pd-main-button img{width:100%;height:min(58dvh,620px);object-fit:contain;background:#fff;border-radius:18px}.pd-thumbs{display:flex;justify-content:center;gap:8px;margin-top:10px}.pd-thumb{width:52px;height:62px;border:2px solid transparent;border-radius:10px;padding:0;background:#fff;overflow:hidden}.pd-thumb.active{border-color:var(--wine)}.pd-thumb img{width:100%;height:100%;object-fit:cover}.pd-info{padding:22px 18px 28px}.pd-info h2{font-size:clamp(1.65rem,5vw,2.4rem)!important}.pd-description-block{margin:18px 0;padding:16px;border-radius:15px;background:var(--brand-bg,#faf7f8);line-height:1.6;white-space:pre-line}.pd-description-block h3{font:800 .95rem Inter,system-ui,sans-serif!important;margin:0 0 7px}.stock-state{display:inline-flex;padding:7px 10px;border-radius:999px;background:#eaf8ef;color:#18733c}.stock-state.sold-out{background:#efedef;color:#55515a}.pd-actions{position:sticky;bottom:0}.pd-actions button:disabled{filter:grayscale(1);opacity:.55;cursor:not-allowed}
.image-viewer{position:fixed;inset:0;z-index:120;background:#111;display:none;overflow:auto}.image-viewer.show{display:grid;place-items:center}.image-viewer img{max-width:none;width:min(92vw,900px);height:auto;transition:width .15s;touch-action:pinch-zoom}.viewer-close{position:fixed;right:16px;top:16px;z-index:2;width:44px;height:44px;border:0;border-radius:50%;background:#fff;color:#111;font-size:1.4rem}.viewer-controls{position:fixed;bottom:22px;left:50%;transform:translateX(-50%);display:flex;gap:8px;background:#ffffffdf;padding:7px;border-radius:999px}.viewer-controls button{border:0;background:#fff;border-radius:50%;width:40px;height:40px;font-size:1.2rem}
@media(min-width:700px){.category-strip{grid-auto-columns:14%}.category-card{min-height:88px}.promo{min-height:62px}.pd-layout{grid-template-columns:minmax(0,1.25fr) minmax(330px,.75fr)}.pd-gallery-wrap{min-height:calc(100dvh - 78px);display:flex;flex-direction:column;justify-content:center}.pd-info{padding:70px 34px 40px}.pd-main-button img{height:70dvh}.pd-actions{grid-column:2;position:fixed;right:max(0px,calc((100vw - 1040px)/2));bottom:0;width:min(40%,416px)}}
@media(max-width:480px){.product-photo-slots{grid-template-columns:1fr}.product-photo-slot{display:grid;grid-template-columns:90px 1fr;gap:8px;align-items:center}.product-photo-slot img{grid-row:1/4}.portal-home{padding-top:34px}.store-action-row{gap:8px}.store-action-row .contact-button{flex:1 1 calc(50% - 5px);min-width:0;max-width:190px;padding:11px 10px;font-size:.78rem}}
`;
document.head.appendChild(v7Style);

function isPortalHome(){return !new URLSearchParams(location.search).get('tienda')}
function setThemeColor(color){const safe=/^#[0-9a-f]{6}$/i.test(color||'')?color:'#24232a';let meta=document.querySelector('meta[name="theme-color"]');if(!meta){meta=document.createElement('meta');meta.name='theme-color';document.head.append(meta)}meta.content=safe;document.documentElement.style.setProperty('--system-bar-color',safe)}
function arrangeBrandHeader(){const topbar=document.querySelector('.topbar'),identity=topbar?.firstElementChild,kicker=document.querySelector('.brand-kicker'),brand=document.querySelector('.brand'),logo=document.querySelector('#brandLogo');if(!topbar||!identity||!kicker||!brand)return;identity.classList.add('brand-identity');let copy=identity.querySelector('.brand-copy');if(!copy){copy=document.createElement('div');copy.className='brand-copy';copy.append(kicker,brand);identity.append(copy)}if(logo&&logo.parentElement!==identity)identity.insertBefore(logo,copy)}
function updateCompactHeader(){document.querySelector('.topbar')?.classList.toggle('is-compact',window.scrollY>64)}
window.addEventListener('scroll',updateCompactHeader,{passive:true});
function isSuperUser(user){return Boolean(user&&(user.id===SUPERADMIN_USER_ID||user.app_metadata?.role==='superadmin'))}
async function authenticatedUser(){
 if(supabaseClient.auth.getUser){const {data,error}=await supabaseClient.auth.getUser();return error?null:data?.user||null}
 const {data}=await supabaseClient.auth.getSession();return data?.session?.user||null;
}
function portalShell(inner){
 document.body.classList.add('portal-mode');activeBusiness=null;document.title='Acceso a tiendas';setThemeColor('#24232a');
 document.querySelector('.brand-kicker').textContent='Administración privada';document.querySelector('.brand').textContent='Portal de tiendas';
 let portal=document.querySelector('#portalHome');if(!portal){portal=document.createElement('section');portal.id='portalHome';portal.className='portal-home';document.querySelector('main').appendChild(portal)}
 portal.innerHTML=inner;return portal;
}
function iconForCategory(name,stored=''){
 const legacy=['◇','◒','♢','♚','◉','✧','✦'];if(stored&&!legacy.includes(stored))return stored;
 const value=String(name||'').toLowerCase();
 if(value.includes('falda'))return '👗';if(value.includes('blusa')||value.includes('polera'))return '👚';if(value.includes('vestido'))return '👗';if(value.includes('cintur'))return '👜';if(value.includes('iglesia'))return '✨';if(value.includes('chaqueta')||value.includes('abrigo'))return '🧥';if(value.includes('zapato')||value.includes('calzado'))return '👠';if(value.includes('pañuelo'))return '🧣';if(value.includes('billetera'))return '👛';if(value.includes('cartera')||value.includes('bolso')||value.includes('accesor'))return '👜';return '✦';
}
function variantOptionsOf(product){const raw=product?.variant_options;return raw&&typeof raw==='object'&&!Array.isArray(raw)?{image_colors:Array.isArray(raw.image_colors)?raw.image_colors.map(String).slice(0,3):[],combinations:Array.isArray(raw.combinations)?raw.combinations.filter(x=>x&&typeof x==='object').map(x=>({color:String(x.color||'Consultar'),size:String(x.size||'Única'),availability:x.availability==='sold_out'?'sold_out':'available'})).slice(0,120):[]}:{image_colors:[],combinations:[]}}
function normVariant(value){return String(value||'').trim().toLocaleLowerCase('es-CL')}
function findCombination(product,color,size){const options=variantOptionsOf(product),keyColor=normVariant(color),keySize=normVariant(size);return options.combinations.find(x=>normVariant(x.color)===keyColor&&normVariant(x.size)===keySize)||null}
function combinationAvailable(product,color,size){const options=variantOptionsOf(product);if(!options.combinations.length)return product.availability!=='sold_out';return findCombination(product,color,size)?.availability==='available'}
function productHasAvailability(product){const options=variantOptionsOf(product);return options.combinations.length?options.combinations.some(x=>x.availability==='available'):product.availability!=='sold_out'}
function colorSwatch(name){const value=normVariant(name),colors={beige:'#d8c2a5',negro:'#171717',blanco:'#ffffff',burdeo:'#772640',rojo:'#c62828',rosado:'#df86aa',rosa:'#df86aa',verde:'#2e7d52',azul:'#3567a8','azul marino':'#15345a',morado:'#7350a3',lila:'#a98ac8',amarillo:'#e0b72f',naranjo:'#df7a2e',café:'#795548',cafe:'#795548',gris:'#8b8b8b',dorado:'#c7a33a',plateado:'#aeb4bb'};return colors[value]||'#ddd'}

async function renderBusinessPortal(){
 const portal=portalShell('<div class="portal-intro"><span class="portal-mark">⌂</span><p class="eyebrow">Acceso privado</p><h2>Portal de administración</h2><p>Ingresa con tu usuario para administrar la tienda que tienes asignada.</p></div><div class="portal-empty">Comprobando acceso…</div>');
 if(!authReady())return;
 const user=await authenticatedUser();
 if(!user){portal.innerHTML='<div class="portal-intro"><span class="portal-mark">⌂</span><p class="eyebrow">Acceso privado</p><h2>Administra tu tienda</h2><p>El portal general no es público. Ingresa con el usuario y contraseña de tu negocio.</p></div><div class="portal-empty portal-login"><strong>¿Tienes una cuenta de administración?</strong><button class="btn btn-wine" type="button" onclick="openProfile()">Ingresar</button><small>Los clientes deben abrir el enlace o código QR de la tienda.</small></div>';return}
 activeUser=user;
 if(!isSuperUser(user)){
  const business=await resolveBusinessForUser(user);managedBusiness=business;
  if(business){location.replace(appBaseUrl+'?tienda='+encodeURIComponent(business.slug));return}
  portal.innerHTML='<div class="portal-intro"><span class="portal-mark">!</span><p class="eyebrow">Cuenta sin tienda</p><h2>No tienes una página asignada</h2><p>Solicita al superadministrador que revise el acceso de tu perfil.</p></div>';return;
 }
 document.title='Directorio privado — Superadministración';document.querySelector('.brand-kicker').textContent='Superadministración';document.querySelector('.brand').textContent='Todas las tiendas';
 const {data,error}=await supabaseClient.from('businesses').select('*').order('created_at',{ascending:true});
 if(error){portal.innerHTML+='<div class="portal-empty">No fue posible cargar las tiendas. Intenta nuevamente.</div>';return}
 const rows=data||[];
 portal.innerHTML=`<div class="portal-intro"><span class="portal-mark">✦</span><p class="eyebrow">Superadministración</p><h2>Todas las tiendas</h2><p>Solo tu cuenta puede ver este directorio, crear páginas y administrar todos los perfiles.</p></div><div class="portal-admin-actions"><button class="btn btn-wine" type="button" onclick="managedBusiness=null;openAdminDashboard('profiles')">＋ Crear y administrar tiendas</button></div>${rows.length?`<div class="portal-grid">${rows.map(b=>{const hero=webUrl(b.hero_image_url),logo=webUrl(b.logo_url);return `<a class="portal-card" href="?tienda=${encodeURIComponent(b.slug)}"><div class="portal-cover" style="${hero?`background-image:url(${JSON.stringify(hero)});background-size:cover;background-position:center`:''}">${logo?`<img class="portal-logo" src="${esc(logo)}" alt="Logo de ${esc(b.name)}">`:''}</div><div class="portal-card-body"><span class="portal-open">Entrar →</span><h3>${esc(b.name)}</h3><span>${b.published?'Página activa':'Página no publicada'}</span></div></a>`}).join('')}</div>`:'<div class="portal-empty">Todavía no has creado tiendas.</div>'}`;
}

loadStore=async function(){
 if(isPortalHome()){await renderBusinessPortal();return}
 document.body.classList.remove('portal-mode');document.querySelector('#portalHome')?.remove();
 const slug=new URLSearchParams(location.search).get('tienda'),user=authReady()?await authenticatedUser():null;
 if(user&&!isSuperUser(user)){const assigned=await resolveBusinessForUser(user);if(assigned&&assigned.slug!==slug){location.replace(appBaseUrl+'?tienda='+encodeURIComponent(assigned.slug));return}}
 const business=await fetchBusiness(slug);
 if(!business){activeBusiness=null;products.splice(0);cats.splice(0,cats.length,'Todas');renderCats();render();count.textContent='Tienda no disponible';return}
 applyBusiness(business);
 const [productResult,categoryResult]=await Promise.all([
  supabaseClient.from('products').select('*').eq('business_id',business.id).eq('active',true).order('sort_order').order('created_at',{ascending:false}),
  supabaseClient.from('categories').select('*').eq('business_id',business.id).eq('active',true).order('sort_order')
 ]);
 if(productResult.error){console.error(productResult.error);toast('No se pudo cargar el catálogo');return}
 const categoryRows=categoryResult.data||[];
 products.splice(0,products.length,...(productResult.data||[]).map(p=>{const images=(p.images?.length?p.images:[p.image_url]).filter(Boolean).slice(0,3),variant_options=variantOptionsOf(p),base={id:p.id,dbId:p.id,name:p.name,cat:p.category,price:Number(p.price),old:Number(p.old_price||0),sizes:p.sizes?.length?p.sizes:['Única'],colors:p.colors?.length?p.colors:['Consultar'],img:images[0]||makeImg(p.name,'#ead2da','#fff7f9'),images,desc:p.description||'',availability:p.availability||(Number(p.stock||0)>0?'available':'sold_out'),variant_options};base.availability=productHasAvailability(base)?'available':'sold_out';return base}));
 const names=categoryRows.map(c=>c.name),extras=products.map(p=>p.cat).filter(n=>!names.includes(n));cats.splice(0,cats.length,'Todas',...names,...new Set(extras));window.categoryIcons=Object.fromEntries(categoryRows.map(c=>[c.name,iconForCategory(c.name,c.icon)]));
 if(!cats.includes(selectedCat))selectedCat='Todas';cart=cart.filter(x=>{const p=products.find(p=>p.id===x.id);return p&&combinationAvailable(p,x.color,x.size)});favs=favs.filter(id=>products.some(p=>p.id===id));save();renderCats();render();
};

applyBusiness=function(b){
 v7ApplyBusiness(b);document.body.classList.remove('portal-mode');setThemeColor(colorValue(b.primary_color,'#772640'));arrangeBrandHeader();updateCompactHeader();
 let actions=document.querySelector('#storeActions');if(!actions){actions=document.createElement('section');actions.id='storeActions';document.querySelector('.hero').after(actions)}
 const info=document.querySelector('#storeLinks'),links=info?.querySelector('.brand-contact');actions.replaceChildren();
 if(links){links.className='store-action-row';links.querySelectorAll('a').forEach(link=>{const label=link.textContent.trim();link.className='btn contact-button';link.dataset.contact=label.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,'-');link.setAttribute('aria-label',label);link.innerHTML=`<span class="contact-icon" aria-hidden="true">${contactIcon(label)}</span><span>${esc(label)}</span>`});actions.append(links)}
 actions.hidden=!actions.querySelector('a');
 if(info)info.hidden=!info.children.length;
};

function contactIcon(label){
 const common='viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"';
 const icons={
  WhatsApp:`<svg ${common}><path d="M20.5 11.7a8.4 8.4 0 0 1-12.4 7.4L3 20.5l1.4-4.9A8.4 8.4 0 1 1 20.5 11.7Z"/><path d="M8.2 7.8c.2-.5.4-.5.7-.5h.5c.2 0 .4.1.5.4l.8 2c.1.3 0 .5-.2.7l-.7.8c-.2.2-.1.4 0 .6.7 1.3 1.7 2.3 3 3 .2.1.4.2.6 0l.9-1.1c.2-.2.4-.3.7-.2l2 .9c.3.1.4.3.4.5 0 .3-.2 1.4-.8 1.9-.5.5-1.2.8-2 .8-.5 0-1.2-.1-2-.4-1.2-.4-2.8-1.2-4.4-2.7-1.3-1.2-2.2-2.7-2.5-3.7-.4-1-.4-1.8-.1-2.4.2-.3.4-.5.6-.6Z" fill="currentColor" stroke="none"/></svg>`,
  Instagram:`<svg ${common}><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>`,
  TikTok:`<svg ${common}><path d="M15 4v10.3a4.3 4.3 0 1 1-3.6-4.2"/><path d="M15 4c.7 2.4 2.2 3.8 4.5 4"/></svg>`,
  Facebook:`<svg ${common}><path d="M14 21v-8h3l.5-3H14V8.2c0-.9.3-1.7 1.8-1.7H18V3.8c-.6-.1-1.5-.2-2.6-.2-2.7 0-4.4 1.6-4.4 4.6V10H8v3h3v8"/></svg>`,
  'Cómo llegar':`<svg ${common}><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>`,
  'Sitio web':`<svg ${common}><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></svg>`,
  Llamar:`<svg ${common}><path d="M6.6 3.8 9 7.7 7.6 9.4c1.3 2.7 3.3 4.7 6 6l1.7-1.4 3.9 2.4-.7 3c-.2.8-.9 1.3-1.7 1.3C9.3 20.2 3.8 14.7 3.3 7.2c0-.8.5-1.5 1.3-1.7l2-.5Z"/></svg>`,
  Correo:`<svg ${common}><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg>`
 };
 return icons[label]||icons['Sitio web'];
}

renderCats=function(){categories.innerHTML=cats.map(c=>`<button class="category-card ${selectedCat===c?'active':''}" data-cat="${escapeHtml(c)}" onclick="setCat(this.dataset.cat)"><span class="cat-icon">${c==='Todas'?'✨':escapeHtml(iconForCategory(c,window.categoryIcons?.[c]))}</span><strong>${escapeHtml(c)}</strong></button>`).join('')};
render=function(){
 const q=search.value.toLowerCase(),s=size.value,p=Number(priceFilter.value||0);const rows=products.filter(x=>(selectedCat==='Todas'||x.cat===selectedCat)&&(!q||(x.name+' '+x.cat).toLowerCase().includes(q))&&(!s||x.sizes.includes(s))&&(!p||x.price<=p));count.textContent=rows.length+' productos';
 grid.innerHTML=rows.map(x=>{const sold=x.availability==='sold_out',photoCount=x.images?.length||1;return `<article class="card"><div class="photo" onclick="openProduct('${x.id}')"><img loading="lazy" decoding="async" src="${escapeHtml(x.img)}" alt="${escapeHtml(x.name)}">${x.old?'<span class="sale">OFERTA</span>':''}${sold?'<span class="sale sold">AGOTADO</span>':''}<button class="heart" aria-label="Favorito" onclick="event.stopPropagation();toggleFav('${x.id}')">${favs.includes(x.id)?'♥':'♡'}</button>${photoCount>1?`<span class="photo-count">▣ ${photoCount}</span>`:''}<span class="availability-badge ${sold?'sold-out':''}">${sold?'Agotado':'Disponible'}</span></div><div class="card-body"><span class="cat">${escapeHtml(x.cat)}</span><h3>${escapeHtml(x.name)}</h3><div class="price-line"><span class="price">${CLP(x.price)}</span>${x.old?`<span class="old">${CLP(x.old)}</span>`:''}</div><button class="quick" onclick="openProduct('${x.id}')">Ver producto</button></div></article>`}).join('')||'<div class="empty" style="grid-column:1/-1">No encontramos productos con esos filtros.</div>';
};

resolveBusinessForUser=async function(user){
 if(user.id===SUPERADMIN_USER_ID||user.app_metadata?.role==='superadmin'){window.accessExpired=false;const slug=new URLSearchParams(location.search).get('tienda');return slug?await fetchBusiness(slug):null}
 const {data:membership}=await supabaseClient.from('business_members').select('business_id,trial_ends_at').eq('user_id',user.id).eq('active',true).maybeSingle();if(!membership?.business_id)return null;window.accessExpired=Boolean(membership.trial_ends_at&&new Date(membership.trial_ends_at)<=new Date());const {data}=await supabaseClient.from('businesses').select('*').eq('id',membership.business_id).maybeSingle();return data;
};

accountView=async function(user){
 activeUser=user;const isSuper=isSuperUser(user),business=await resolveBusinessForUser(user);managedBusiness=business;
 if(!isSuper&&business&&isPortalHome()){location.replace(appBaseUrl+'?tienda='+encodeURIComponent(business.slug));return}
 if(isSuper&&isPortalHome())await renderBusinessPortal();
 profileContent.innerHTML=`<div class="profile-head"><div class="profile-avatar">${isSuper?'SA':'AD'}</div><div><span class="admin-badge">${isSuper?'✦ Superadministrador':'Administrador'}</span><h2 class="profile-title">${isSuper?'Panel principal':esc(business?.name||'Mi tienda')}</h2></div></div><div class="status-card"><div class="status-row"><span>Usuario</span><strong>${esc(user.user_metadata?.username||user.email)}</strong></div><div class="status-row"><span>Estado</span><strong class="status-ok">Activo</strong></div><div class="status-row"><span>Tienda</span><strong>${esc(business?.name||(isSuper?'Todas las páginas':'Sin asignar'))}</strong></div></div>${business?`<button class="btn btn-wine" style="width:100%;margin-bottom:9px" onclick="openAdminDashboard()">⚙ Administrar esta tienda</button><button class="btn btn-outline" style="width:100%;margin-bottom:9px" onclick="openPublicStore()">Ver tienda pública</button>`:''}${isSuper?'<button class="btn btn-wine" style="width:100%;margin-bottom:9px" onclick="managedBusiness=null;openAdminDashboard(\'profiles\')">＋ Crear y administrar páginas</button>':''}<button class="btn btn-outline" style="width:100%" id="logoutButton">Cerrar sesión</button>`;document.querySelector('#logoutButton').onclick=logoutProfile;
};

openAdminDashboard=async function(tabName='settings'){
 if(window.accessExpired&&activeUser?.id!==SUPERADMIN_USER_ID){closeModal('profileModal');adminModal.classList.add('show');document.body.classList.add('admin-mode');adminContent.innerHTML='<div class="admin-card expired-access"><h2>Tu período de administración venció</h2><p>Puedes seguir viendo tu tienda pública, pero no editarla.</p></div>';return}
 closeModal('profileModal');adminModal.classList.add('show');document.body.classList.add('admin-mode');window.scrollTo(0,0);const back=document.querySelector('#adminModal>.sheet>.close');back.textContent='← Volver';back.setAttribute('aria-label','Volver');
 adminContent.innerHTML='<div class="empty">Cargando administración…</div>';const isSuper=activeUser?.id===SUPERADMIN_USER_ID||activeUser?.app_metadata?.role==='superadmin';const business=managedBusiness||await resolveBusinessForUser(activeUser);managedBusiness=business;
 if(!business&&!isSuper){adminContent.innerHTML='<div class="empty">Tu cuenta no tiene una tienda asignada.</div>';return}
 if(!business){adminContent.innerHTML='<p class="eyebrow">Superadministración</p><h2 class="profile-title">Páginas y perfiles</h2><div class="admin-tabs"><button class="admin-tab active" data-tab="profiles">Páginas y perfiles</button></div><section class="admin-panel active" data-panel="profiles"></section>';await renderProfiles();return}
 adminContent.innerHTML=`<p class="eyebrow">Administración</p><h2 class="profile-title">${esc(business.name)}</h2><div class="admin-tabs"><button class="admin-tab" data-tab="settings">Ajustes</button><button class="admin-tab" data-tab="products">Productos</button><button class="admin-tab" data-tab="categories">Categorías</button><button class="admin-tab" data-tab="share">Link y QR</button>${isSuper?'<button class="admin-tab" data-tab="profiles">Páginas</button>':''}</div><section class="admin-panel" data-panel="settings"></section><section class="admin-panel" data-panel="products"></section><section class="admin-panel" data-panel="categories"></section><section class="admin-panel" data-panel="share"></section><section class="admin-panel" data-panel="profiles"></section>`;
 adminContent.querySelectorAll('.admin-tab').forEach(btn=>btn.onclick=()=>showAdminTab(btn.dataset.tab));renderSettings();await renderProductAdmin();await renderCategoryAdmin();renderShare();if(isSuper)await renderProfiles();showAdminTab(tabName==='profiles'&&isSuper?'profiles':tabName);
};

renderSettings=function(){
 v7RenderSettings();
 for(const key of ['logo','hero_image']){const input=document.querySelector(`#${key}File`);if(!input)continue;const field=input.closest('.field');field.classList.add('image-field-simple');field.querySelector(`input[name="remove_${key}"]`)?.closest('label')?.remove();const small=field.querySelector('small');if(small)small.textContent='Selecciona una imagen nueva para reemplazar la actual. JPG, PNG o WebP · máximo 5 MB.';const tools=document.createElement('div');tools.className='image-tools';tools.innerHTML='<button type="button">Quitar imagen</button>';tools.querySelector('button').onclick=()=>{field.querySelector(`input[name="${key}_url"]`).value='';field.querySelectorAll('img').forEach(img=>img.remove());input.value='';toast('La imagen se quitará cuando guardes los ajustes')};field.append(tools)}
};

function productPhotoSlots(p){const images=(p.images?.length?p.images:[p.image_url]).filter(Boolean).slice(0,3),imageColors=variantOptionsOf(p).image_colors;return `<div class="product-photo-slots">${[0,1,2].map(i=>{const url=images[i]||'';return `<div class="product-photo-slot" data-slot="${i}"><img src="${esc(url||makeImg('Foto '+(i+1),'#eee6ef','#faf7fa'))}" alt="Foto ${i+1}"><div><label for="productImage${i}">${url?'Reemplazar foto '+(i+1):'Agregar foto '+(i+1)}</label><input id="productImage${i}" type="file" accept="image/jpeg,image/png,image/webp"><input type="hidden" name="existing_image_${i}" value="${esc(url)}"><label class="photo-color-field">Color de esta foto<input name="image_color_${i}" list="productColorOptions" value="${esc(imageColors[i]||'')}" placeholder="Ej. Beige"></label><button class="slot-remove" type="button">Quitar</button></div></div>`}).join('')}</div>`}
function renderVariantMatrix(product={}){const form=document.querySelector('#productForm'),matrix=form?.querySelector('#variantMatrix');if(!form||!matrix)return;const present=new Map([...matrix.querySelectorAll('input[data-color]')].map(x=>[normVariant(x.dataset.color)+'|'+normVariant(x.dataset.size),x.checked])),stored=new Map(variantOptionsOf(product).combinations.map(x=>[normVariant(x.color)+'|'+normVariant(x.size),x.availability==='available'])),sizes=list(form.elements.sizes.value);if(!sizes.length)sizes.push('Única');const colors=list(form.elements.colors.value);if(!colors.length)colors.push('Consultar');const availableByDefault=product.availability!=='sold_out';matrix.style.setProperty('--variant-cols',String(sizes.length));matrix.innerHTML=`<div class="variant-row"><strong>Color</strong>${sizes.map(size=>`<span class="variant-head">${esc(size)}</span>`).join('')}</div>${colors.map(color=>`<div class="variant-row"><strong>${esc(color)}</strong>${sizes.map(size=>{const key=normVariant(color)+'|'+normVariant(size),checked=present.has(key)?present.get(key):(stored.has(key)?stored.get(key):availableByDefault);return `<label class="variant-cell"><input type="checkbox" data-color="${esc(color)}" data-size="${esc(size)}" ${checked?'checked':''}><span>${checked?'Disponible':'Agotado'}</span></label>`}).join('')}</div>`).join('')}`;matrix.querySelectorAll('input').forEach(input=>input.onchange=()=>{input.nextElementSibling.textContent=input.checked?'Disponible':'Agotado';updateVariantSummary()});const datalist=form.querySelector('#productColorOptions');if(datalist)datalist.innerHTML=colors.map(color=>`<option value="${esc(color)}">`).join('');updateVariantSummary()}
function updateVariantSummary(){const form=document.querySelector('#productForm'),inputs=[...(form?.querySelectorAll('#variantMatrix input')||[])],available=inputs.filter(x=>x.checked).length;const summary=form?.querySelector('#variantSummary');if(summary)summary.textContent=`${available} combinación${available===1?'':'es'} disponible${available===1?'':'s'} de ${inputs.length}.`}
productForm=function(p={}){
 const panel=adminContent.querySelector('[data-panel=products]');panel.innerHTML=`<form id="productForm" class="admin-grid"><div class="editor-heading"><div><h3>${p.id?'Editar producto':'Nuevo producto'}</h3><p class="help-copy">Relaciona cada fotografía con un color y controla qué combinaciones se pueden comprar.</p></div><button type="button" class="btn btn-outline" onclick="renderProductAdmin()">Volver</button></div><div class="editor-layout"><section class="admin-card"><h3>Información</h3><div class="field"><label for="editName">Nombre</label><input id="editName" name="name" required minlength="2" maxlength="120" value="${esc(p.name)}"></div><div class="field"><label for="editCategory">Categoría</label><select id="editCategory" name="category" required>${[...new Set([...adminCategories.filter(c=>c.active).map(c=>c.name),p.category||'Productos'])].map(name=>`<option value="${esc(name)}" ${name===(p.category||'Productos')?'selected':''}>${esc(name)}</option>`).join('')}</select></div><div class="two-col"><div class="field"><label for="editPrice">Precio</label><input id="editPrice" name="price" type="number" min="0" required value="${esc(p.price??'')}"></div><div class="field"><label for="editOldPrice">Precio anterior</label><input id="editOldPrice" name="old_price" type="number" min="0" value="${esc(p.old_price||'')}"></div></div><div class="field"><label for="editDescription">Descripción y detalles</label><textarea id="editDescription" name="description" maxlength="3000">${esc(p.description)}</textarea></div><div class="two-col"><div class="field"><label for="editSizes">Tallas</label><input id="editSizes" name="sizes" value="${esc((p.sizes||[]).join(', '))}" placeholder="S, M, L"></div><div class="field"><label for="editColors">Colores</label><input id="editColors" name="colors" value="${esc((p.colors||[]).join(', '))}" placeholder="Beige, Negro"></div></div><label><input name="active" type="checkbox" ${p.active!==false?'checked':''}> Visible en la tienda</label></section><aside class="admin-card photo-editor"><h3>Fotos por color</h3><datalist id="productColorOptions"></datalist>${productPhotoSlots(p)}<p class="help-copy">Máximo 3 fotos. Escribe debajo de cada una el color que representa.</p></aside></div><section class="admin-card variant-admin-card"><h3>Disponibilidad por color y talla</h3><p class="help-copy">Marca solamente las combinaciones que pueden comprarse. Las agotadas seguirán visibles.</p><div id="variantMatrix" class="variant-matrix"></div><p id="variantSummary" class="variant-summary"></p></section><p class="profile-message" id="productMessage" role="status"></p><div class="editor-footer"><button type="button" class="btn btn-outline" onclick="renderProductAdmin()">Cancelar</button><button class="btn btn-wine" type="submit">Guardar producto</button></div></form>`;
 document.querySelectorAll('.product-photo-slot').forEach(slot=>{const input=slot.querySelector('input[type=file]'),img=slot.querySelector('img'),hidden=slot.querySelector('input[type=hidden]'),color=slot.querySelector('[name^=image_color_]');input.onchange=()=>{const file=input.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){toast('Usa JPG, PNG o WebP de hasta 5 MB');input.value='';return}img.src=URL.createObjectURL(file)};slot.querySelector('.slot-remove').onclick=()=>{input.value='';hidden.value='';color.value='';img.src=makeImg('Foto '+(Number(slot.dataset.slot)+1),'#eee6ef','#faf7fa')}});const form=document.querySelector('#productForm');form.elements.sizes.addEventListener('input',()=>renderVariantMatrix(p));form.elements.colors.addEventListener('input',()=>renderVariantMatrix(p));renderVariantMatrix(p);form.onsubmit=e=>saveProduct(e,p.id);window.scrollTo(0,0);
};

saveProduct=guardedSubmit(async function(e,id){
 e.preventDefault();const form=e.target,f=new FormData(form),message=form.querySelector('#productMessage');message.textContent='Guardando producto…';const images=[],image_colors=[];
 for(let i=0;i<3;i++){let url=String(f.get('existing_image_'+i)||'');const file=form.querySelector('#productImage'+i)?.files[0];if(file){url=await uploadImage(file);if(!url){message.textContent='No se pudo subir la foto '+(i+1)+'.';return}}if(url&&!images.includes(url)){images.push(url);image_colors.push(String(f.get('image_color_'+i)||'').trim())}}
 const sizes=list(f.get('sizes')),colors=list(f.get('colors')),combinations=[...form.querySelectorAll('#variantMatrix input[data-color]')].map(input=>({color:input.dataset.color,size:input.dataset.size,availability:input.checked?'available':'sold_out'})),availability=combinations.some(x=>x.availability==='available')?'available':'sold_out',variant_options={image_colors,combinations};const payload={business_id:managedBusiness.id,name:String(f.get('name')).trim(),category:String(f.get('category')).trim(),price:Number(f.get('price')),old_price:Number(f.get('old_price')||0),availability,stock:availability==='available'?1:0,description:String(f.get('description')).trim(),sizes,colors,images,image_url:images[0]||'',variant_options,active:f.get('active')==='on',updated_at:new Date().toISOString()};
 const result=await (id?supabaseClient.from('products').update(payload).eq('id',id):supabaseClient.from('products').insert(payload));if(result.error){message.textContent=result.error.message;return}toast('Producto guardado');await renderProductAdmin();await loadStore();
});

renderProductAdmin=async function(){
 const panel=adminContent.querySelector('[data-panel=products]');if(!panel||!managedBusiness)return;const {data,error}=await supabaseClient.from('products').select('*').eq('business_id',managedBusiness.id).order('sort_order').order('created_at',{ascending:false});adminProductsCache=data||[];panel.innerHTML='<button class="btn btn-wine" style="width:100%;margin-bottom:12px" onclick="productForm()">＋ Subir producto</button><div class="admin-list" id="adminProductList"></div>';const listEl=panel.querySelector('#adminProductList');if(error){listEl.innerHTML='<div class="notice">'+esc(error.message)+'</div>';return}listEl.innerHTML=adminProductsCache.map((p,i)=>{const sold=!productHasAvailability(p),availableCount=variantOptionsOf(p).combinations.filter(x=>x.availability==='available').length;return `<div class="admin-product"><img src="${esc(p.image_url||p.images?.[0]||makeImg(p.name,'#ead2da','#fff7f9'))}"><div><strong>${esc(p.name)}</strong><div class="price">${CLP(Number(p.price))}</div><small>${p.active?'Visible':'Oculto'} · ${sold?'Agotado':availableCount?availableCount+' variantes disponibles':'Disponible'} · ${esc(p.category)}</small></div><div class="small-actions"><button onclick="productForm(adminProductsCache[${i}])">Editar</button><button onclick="duplicateProductV7(${i})">Duplicar</button><button class="danger" onclick="deleteProduct('${p.id}')">Eliminar</button></div></div><details class="quick-edit"><summary>Edición rápida</summary><div class="quick-fields"><label>Precio <input type="number" min="0" value="${Number(p.price)}"></label><label>Estado <select><option value="available" ${sold?'':'selected'}>Todo disponible</option><option value="sold_out" ${sold?'selected':''}>Todo agotado</option></select></label><label><input type="checkbox" ${p.active?'checked':''}> Visible</label><button type="button" onclick="quickSaveProductV7('${p.id}',this)">Guardar</button><button type="button" ${i===0?'disabled':''} onclick="moveProduct(${i},-1)">Subir</button><button type="button" ${i===adminProductsCache.length-1?'disabled':''} onclick="moveProduct(${i},1)">Bajar</button></div></details>`}).join('')||'<div class="empty">Todavía no hay productos.</div>';
};
async function quickSaveProductV7(id,button){const box=button.closest('.quick-fields'),inputs=box.querySelectorAll('input'),availability=box.querySelector('select').value,product=adminProductsCache.find(p=>p.id===id),options=variantOptionsOf(product);if(options.combinations.length)options.combinations=options.combinations.map(x=>({...x,availability}));const payload={price:Number(inputs[0].value||0),availability,stock:availability==='available'?1:0,variant_options:options,active:inputs[1].checked,updated_at:new Date().toISOString()},result=await supabaseClient.from('products').update(payload).eq('id',id);if(result.error)return toast(result.error.message);toast('Cambios guardados');await renderProductAdmin();await loadStore()}
async function duplicateProductV7(i){const p={...adminProductsCache[i]};delete p.id;delete p.created_at;p.name+=' (copia)';p.active=false;const {error}=await supabaseClient.from('products').insert(p);if(error)return toast(error.message);toast('Producto duplicado como oculto');await renderProductAdmin()}

function ensureImageViewer(){let viewer=document.querySelector('#imageViewer');if(viewer)return viewer;viewer=document.createElement('div');viewer.id='imageViewer';viewer.className='image-viewer';viewer.innerHTML='<button class="viewer-close" aria-label="Cerrar">×</button><img alt="Imagen ampliada"><div class="viewer-controls"><button type="button" data-delta="-.25">−</button><button type="button" data-delta="reset">1:1</button><button type="button" data-delta=".25">＋</button></div>';viewer.querySelector('.viewer-close').onclick=()=>viewer.classList.remove('show');viewer.querySelectorAll('[data-delta]').forEach(btn=>btn.onclick=()=>{const img=viewer.querySelector('img'),delta=btn.dataset.delta;if(delta==='reset')viewer.dataset.zoom='1';else viewer.dataset.zoom=String(Math.max(.5,Math.min(3,Number(viewer.dataset.zoom||1)+Number(delta))));img.style.width=`min(${92*Number(viewer.dataset.zoom)}vw,${900*Number(viewer.dataset.zoom)}px)`});document.body.append(viewer);return viewer}
function openImageViewer(url,alt){const viewer=ensureImageViewer(),img=viewer.querySelector('img');viewer.dataset.zoom='1';img.style.width='min(92vw,900px)';img.src=url;img.alt=alt||'Producto ampliado';viewer.classList.add('show')}
function setProductImage(i){const track=document.querySelector('.pd-main-track'),buttons=[...document.querySelectorAll('.pd-thumb')];track?.scrollTo({left:(track.clientWidth||1)*i,behavior:'smooth'});buttons.forEach((b,j)=>b.classList.toggle('active',i===j))}
function selectedProductVariant(){return {size:productDetail.querySelector('[data-variant=size] .selected')?.dataset.value||'',color:productDetail.querySelector('[data-variant=color] .selected')?.dataset.value||''}}
function selectedProductVariantAvailable(){const {size,color}=selectedProductVariant();return Boolean(size&&color&&combinationAvailable(current,color,size))}
function refreshProductVariantState(){if(!current)return;const options=variantOptionsOf(current),colorBox=productDetail.querySelector('[data-variant=color]'),sizeBox=productDetail.querySelector('[data-variant=size]');if(!colorBox||!sizeBox)return;let color=colorBox.querySelector('.selected')?.dataset.value||current.colors?.[0]||'Consultar';colorBox.querySelectorAll('.chip').forEach(button=>{const available=!options.combinations.length||current.sizes.some(size=>combinationAvailable(current,button.dataset.value,size));button.classList.toggle('variant-sold',!available);button.title=available?'Disponible en alguna talla':'Agotado en todas las tallas'});let size=sizeBox.querySelector('.selected')?.dataset.value||current.sizes?.[0]||'Única';sizeBox.querySelectorAll('.chip').forEach(button=>{const available=combinationAvailable(current,color,button.dataset.value);button.disabled=!available;button.classList.toggle('variant-sold',!available);if(!available&&button.classList.contains('selected')){button.classList.remove('selected');button.setAttribute('aria-pressed','false')}});let selected=sizeBox.querySelector('.selected');if(!selected){selected=[...sizeBox.querySelectorAll('.chip')].find(button=>!button.disabled);if(selected){selected.classList.add('selected');selected.setAttribute('aria-pressed','true')}}size=selected?.dataset.value||size;const available=Boolean(selected&&combinationAvailable(current,color,size)),status=productDetail.querySelector('.stock-state'),add=productDetail.querySelector('#detailAddCart'),whatsapp=productDetail.querySelector('#detailWhatsapp');status.textContent=available?'Disponible · '+color+' / '+size:'Agotado · '+color+(selected?' / '+size:'');status.classList.toggle('sold-out',!available);add.disabled=!available;add.textContent=available?'Agregar al carrito':'Combinación agotada';whatsapp.disabled=!available;whatsapp.textContent=available?'Comprar por WhatsApp':'No disponible'}
function selectProductVariant(button,type,moveImage=true){if(button.disabled)return;const box=button.closest('.chips');box.querySelectorAll('.chip').forEach(item=>{item.classList.remove('selected');item.setAttribute('aria-pressed','false')});button.classList.add('selected');button.setAttribute('aria-pressed','true');if(type==='color'&&moveImage){const index=variantOptionsOf(current).image_colors.findIndex(color=>normVariant(color)===normVariant(button.dataset.value));if(index>=0)setProductImage(index)}refreshProductVariantState()}
openProduct=function(id){
 current=products.find(p=>String(p.id)===String(id));if(!current)return toast('Este producto ya no está disponible');const images=(current.images?.length?current.images:[current.img]).slice(0,3),options=variantOptionsOf(current),availableColor=current.colors.find(color=>current.sizes.some(size=>combinationAvailable(current,color,size)))||current.colors[0]||'Consultar',variants=(values,type)=>`<div class="chips" data-variant="${type}">${values.map(v=>{const selected=type==='color'&&normVariant(v)===normVariant(availableColor);return `<button class="chip ${type==='color'?'color-chip ':''}${selected?'selected':''}" data-value="${esc(v)}" type="button" onclick="selectProductVariant(this,'${type}')" aria-pressed="${selected}">${type==='color'?`<span class="color-dot" style="--swatch:${esc(colorSwatch(v))}"></span>`:''}${esc(v)}</button>`}).join('')}</div>`;
 productDetail.innerHTML=`<div class="pd-scroll"><div class="pd-layout"><div class="pd-gallery-wrap"><div class="pd-main-track">${images.map((url,i)=>`<button class="pd-main-button" type="button" onclick="openImageViewer((current.images?.length?current.images:[current.img])[${i}],current.name+' foto ${i+1}')"><img loading="eager" src="${esc(url)}" alt="${esc(current.name)} foto ${i+1}"></button>`).join('')}</div>${images.length>1?`<div class="pd-thumbs">${images.map((url,i)=>`<button class="pd-thumb ${i===0?'active':''}" type="button" onclick="setProductImage(${i})"><img src="${esc(url)}" alt="Ver foto ${i+1}">${options.image_colors[i]?`<span class="pd-thumb-label">${esc(options.image_colors[i])}</span>`:''}</button>`).join('')}</div>`:''}</div><div class="pd-info"><p class="eyebrow">${esc(current.cat)}</p><h2>${esc(current.name)}</h2><div class="price-line"><span class="price">${CLP(current.price)}</span>${current.old?`<span class="old">${CLP(current.old)}</span>`:''}</div><p class="stock-state">Disponible</p>${current.desc?`<section class="pd-description-block"><h3>Descripción y detalles</h3><div>${esc(current.desc)}</div></section>`:''}<strong>Color</strong>${variants(current.colors?.length?current.colors:['Consultar'],'color')}<strong>Talla</strong>${variants(current.sizes?.length?current.sizes:['Única'],'size')}</div></div></div><div class="pd-actions"><button class="btn btn-wine" id="detailAddCart">Agregar al carrito</button><button class="wa" id="detailWhatsapp">Comprar por WhatsApp</button></div>`;
 const track=productDetail.querySelector('.pd-main-track');track?.addEventListener('scroll',()=>{const i=Math.round(track.scrollLeft/(track.clientWidth||1));productDetail.querySelectorAll('.pd-thumb').forEach((b,j)=>b.classList.toggle('active',i===j));const mapped=options.image_colors[i],colorButton=[...productDetail.querySelectorAll('[data-variant=color] .chip')].find(button=>normVariant(button.dataset.value)===normVariant(mapped));if(colorButton&&!colorButton.classList.contains('selected'))selectProductVariant(colorButton,'color',false)},{passive:true});productDetail.querySelector('#detailAddCart').onclick=addCart;productDetail.querySelector('#detailWhatsapp').onclick=directWhatsapp;productModal.classList.add('show');productDetail.querySelector('.pd-scroll').scrollTop=0;const initialColorButton=[...productDetail.querySelectorAll('[data-variant=color] .chip')].find(button=>button.classList.contains('selected'));if(initialColorButton){const imageIndex=options.image_colors.findIndex(color=>normVariant(color)===normVariant(initialColorButton.dataset.value));if(imageIndex>=0)setProductImage(imageIndex)}refreshProductVariantState();
};
addCart=function(){if(!current)return toast('Selecciona un producto');if(!selectedProductVariantAvailable())return toast('Esta combinación está agotada');const {size:selectedSize,color:selectedColor}=selectedProductVariant(),key=current.id+'|'+selectedSize+'|'+selectedColor,row=cart.find(x=>x.key===key),imageIndex=variantOptionsOf(current).image_colors.findIndex(color=>normVariant(color)===normVariant(selectedColor)),image=current.images?.[imageIndex]||current.img;if(row)row.qty=Number(row.qty||0)+1;else cart.push({key,id:current.id,name:current.name,price:Number(current.price),img:image,size:selectedSize,color:selectedColor,qty:1});save();closeModal('productModal');openCart();toast('Producto agregado al carrito')};
function orderProductEmoji(product){
 const value=String((product?.name||'')+' '+(product?.cat||product?.category||'')).toLowerCase();
 if(value.includes('corazón')||value.includes('corazon'))return '❤️';
 if(value.includes('falda')||value.includes('vestido'))return '👗';
 if(value.includes('polera')||value.includes('blusa')||value.includes('camisa'))return '👚';
 if(value.includes('zapato')||value.includes('calzado'))return '👠';
 if(value.includes('cintur')||value.includes('cartera')||value.includes('bolso'))return '👜';
 if(value.includes('chaqueta')||value.includes('abrigo'))return '🧥';
 return '✨';
}
function buildWhatsappOrder(items,customer={}){
 const store=String(activeBusiness?.name||'la tienda').toLocaleUpperCase('es-CL'),name=customer.name||'Sin indicar',commune=customer.commune||'Sin indicar',notes=customer.notes||'Sin observaciones';
 const productsText=items.map(x=>`${orderProductEmoji(x)} *${x.name}*\n• Talla: ${x.size||'Única'}\n• Color: ${x.color||'Consultar'}\n• Cantidad: ${Number(x.qty||1)}\n• Precio: ${CLP(Number(x.price||0)*Number(x.qty||1))}`).join('\n\n');
 const total=items.reduce((sum,x)=>sum+Number(x.price||0)*Number(x.qty||1),0);
 return `🛍️ *NUEVO PEDIDO — ${store}*\n\nHola 👋 Quiero realizar el siguiente pedido:\n\n━━━━━━━━━━━━━━\n🛒 *PRODUCTOS*\n\n${productsText}\n\n━━━━━━━━━━━━━━\n💰 *TOTAL: ${CLP(total)}*\n━━━━━━━━━━━━━━\n\n👤 *Cliente:* ${name}\n📍 *Comuna:* ${commune}\n📝 *Observaciones:* ${notes}\n\n✅ Quedo atento/a a la confirmación de disponibilidad y coordinación del pedido. ¡Gracias!`;
}
orderWhatsapp=function(){
 if(!cart.length)return toast('Tu carrito está vacío');const number=(activeBusiness?.whatsapp||'').replace(/\D/g,'');if(!number)return toast('El negocio aún no configuró WhatsApp');
 const customer={name:document.querySelector('#buyerName')?.value.trim()||'Sin indicar',commune:document.querySelector('#buyerCommune')?.value.trim()||'Sin indicar',notes:document.querySelector('#buyerNotes')?.value.trim()||'Sin observaciones'};
 window.open('https://wa.me/'+number+'?text='+encodeURIComponent(buildWhatsappOrder(cart,customer)),'_blank');
};
directWhatsapp=function(){
 if(!current||!selectedProductVariantAvailable())return toast('Esta combinación está agotada');const {size,color}=selectedProductVariant(),number=(activeBusiness?.whatsapp||'').replace(/\D/g,'');if(!number)return toast('El negocio aún no configuró WhatsApp');
 window.open('https://wa.me/'+number+'?text='+encodeURIComponent(buildWhatsappOrder([{...current,size,color,qty:1}],{})),'_blank');
};

renderProfiles=async function(){
 const panel=adminContent.querySelector('[data-panel=profiles]');if(!panel)return;const [{data:businesses,error},{data:members}]=await Promise.all([supabaseClient.from('businesses').select('*').order('created_at',{ascending:false}),supabaseClient.from('business_members').select('user_id,username,role,active,trial_ends_at,business_id').order('created_at',{ascending:false})]);if(error){panel.innerHTML='<div class="notice">'+esc(error.message)+'</div>';return}window.profileMembers=members||[];
 window.businessPages=businesses||[];panel.innerHTML=`<form id="createProfileForm" class="admin-grid"><div class="admin-card"><h3>Crear página y perfil</h3><div class="field"><label>Nombre del negocio</label><input name="businessName" required></div><div class="field"><label>Usuario</label><input name="username" pattern="[a-zA-Z0-9._-]{3,30}" required></div><div class="field"><label>Contraseña</label><input name="password" type="password" minlength="6" required></div><div class="field"><label>Nombre del enlace</label><input name="slug" placeholder="se completa automáticamente"></div></div><p class="profile-message" id="profileCreateMessage"></p><button class="btn btn-wine">Crear perfil y página</button></form><h3 style="margin-top:24px">Páginas creadas</h3><div class="admin-list">${(businesses||[]).map(b=>{const people=(members||[]).filter(m=>m.business_id===b.id);return `<div class="admin-card admin-business-card"><div><strong>${esc(b.name)}</strong><div class="share-link">${esc(appBaseUrl+'?tienda='+b.slug)}</div><small>${b.published?'Pública':'No publicada'} · ${people.length} perfil${people.length===1?'':'es'}</small></div><div class="small-actions"><button onclick="manageBusiness('${b.id}')">Editar página</button><button onclick="location.href='?tienda=${encodeURIComponent(b.slug)}'">Ver</button></div><div>${people.map(m=>`<div class="access-controls"><strong>Usuario: ${esc(m.username)}</strong><label>Vencimiento <input type="date" value="${m.trial_ends_at?m.trial_ends_at.slice(0,10):''}"></label>${m.user_id!==SUPERADMIN_USER_ID?`<div class="small-actions"><button onclick="manageMemberAccess('${m.user_id}',${m.active},this.closest('.access-controls').querySelector('input').value)">Guardar acceso</button><button onclick="resetMemberPassword('${m.user_id}')">Cambiar contraseña</button><button onclick="toggleMember('${m.user_id}','${b.id}',${!m.active})">${m.active?'Suspender':'Activar'}</button></div>`:'<small>Superadministrador</small>'}</div>`).join('')}</div><div class="small-actions business-danger"><button class="danger" onclick="deleteBusinessPage('${b.id}')">Eliminar página</button></div></div>`}).join('')||'<div class="empty">Todavía no hay páginas.</div>'}</div>`;
 const form=panel.querySelector('#createProfileForm');form.onsubmit=createProfile;const businessName=form.elements.businessName,slug=form.elements.slug;businessName.oninput=()=>{if(!slug.dataset.edited)slug.value=slugFrom(businessName.value)};slug.oninput=()=>slug.dataset.edited='1';
};
async function deleteBusinessPage(id){const name=window.businessPages?.find(b=>b.id===id)?.name||'esta página';if(!confirm(`¿Eliminar definitivamente la página “${name}”? Se eliminarán sus productos, categorías, imágenes y perfiles. Esta acción no se puede deshacer.`))return;const typed=prompt('Para confirmar, escribe ELIMINAR');if(typed!=='ELIMINAR')return toast('Eliminación cancelada');const {data,error}=await supabaseClient.functions.invoke('manage-business-admin',{body:{action:'delete_business',businessId:id}});if(error||data?.error)return toast(data?.error||error.message);if(managedBusiness?.id===id)managedBusiness=null;toast('Página eliminada');await renderProfiles();if(isPortalHome())await renderBusinessPortal()}
